// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: DZSJN

#include "../ui.h"
#include "device_nvs.h"
void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3IM1 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_SN3IM1, &ui_img_rectangle_1_png);
    lv_obj_set_width(ui_SN3IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3IM1, 0);
    lv_obj_set_y(ui_SN3IM1, -365);
    lv_obj_set_align(ui_SN3IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // ui_SN3IM2 = lv_img_create(ui_Screen3);
    // lv_img_set_src(ui_SN3IM2, &ui_img_1551342831);
    // lv_obj_set_width(ui_SN3IM2, LV_SIZE_CONTENT);  /// 1
    // lv_obj_set_height(ui_SN3IM2, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_SN3IM2, 110);
    // lv_obj_set_y(ui_SN3IM2, -360);
    // lv_obj_set_align(ui_SN3IM2, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN3IM2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    // lv_obj_clear_flag(ui_SN3IM2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3IM3 = lv_img_create(ui_SN3IM1);
    lv_img_set_src(ui_SN3IM3, &ui_img_1082659618);
    lv_obj_set_width(ui_SN3IM3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3IM3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3IM3, 140);
    lv_obj_set_y(ui_SN3IM3, 0);
    lv_obj_set_align(ui_SN3IM3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3IM3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3IM3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3BAR1 = lv_bar_create(ui_SN3IM1);
    lv_bar_set_value(ui_SN3BAR1, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SN3BAR1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SN3BAR1, 11);
    lv_obj_set_height(ui_SN3BAR1, 20);
    lv_obj_set_x(ui_SN3BAR1, 139);
    lv_obj_set_y(ui_SN3BAR1, 1);
    lv_obj_set_align(ui_SN3BAR1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SN3BAR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3BAR1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3BAR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SN3BAR1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3BAR1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3BAR1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SN3IM6 = lv_img_create(ui_SN3IM1);
    lv_img_set_src(ui_SN3IM6, &ui_img_1292609536);
    lv_obj_set_width(ui_SN3IM6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3IM6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3IM6, 139);
    lv_obj_set_y(ui_SN3IM6, 0);
    lv_obj_set_align(ui_SN3IM6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3IM6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_SN3IM6, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3IM6, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3LAB1 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB1, 170);
    lv_obj_set_y(ui_SN3LAB1, 0);
    lv_obj_set_align(ui_SN3LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB1, "100");
    lv_obj_set_style_text_color(ui_SN3LAB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3LAB2 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB2, 200);
    lv_obj_set_y(ui_SN3LAB2, 0);
    lv_obj_set_align(ui_SN3LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB2, "%");
    lv_obj_set_style_text_color(ui_SN3LAB2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3LAB3 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB3, -200);
    lv_obj_set_y(ui_SN3LAB3, 0);
    lv_obj_set_align(ui_SN3LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB3, "HH");
    lv_obj_set_style_text_color(ui_SN3LAB3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3LAB4 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB4, -160);
    lv_obj_set_y(ui_SN3LAB4, 0);
    lv_obj_set_align(ui_SN3LAB4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB4, "MM");
    lv_obj_set_style_text_color(ui_SN3LAB4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3LAB5 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB5, -181);
    lv_obj_set_y(ui_SN3LAB5, 0);
    lv_obj_set_align(ui_SN3LAB5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB5, ":");
    lv_obj_set_style_text_color(ui_SN3LAB5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3LAB6 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB6, -110);
    lv_obj_set_y(ui_SN3LAB6, 0);
    lv_obj_set_align(ui_SN3LAB6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB6, "DD");
    lv_obj_set_style_text_color(ui_SN3LAB6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3LAB7 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB7, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB7, -85);
    lv_obj_set_y(ui_SN3LAB7, 0);
    lv_obj_set_align(ui_SN3LAB7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB7, "-");
    lv_obj_set_style_text_color(ui_SN3LAB7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3LAB8 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB8, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB8, -60);
    lv_obj_set_y(ui_SN3LAB8, 0);
    lv_obj_set_align(ui_SN3LAB8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB8, "MM");
    lv_obj_set_style_text_color(ui_SN3LAB8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3LAB9 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB9, -35);
    lv_obj_set_y(ui_SN3LAB9, 0);
    lv_obj_set_align(ui_SN3LAB9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB9, "-");
    lv_obj_set_style_text_color(ui_SN3LAB9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3LAB10 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB10, 0);
    lv_obj_set_y(ui_SN3LAB10, 0);
    lv_obj_set_align(ui_SN3LAB10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB10, "YYYY");
    lv_obj_set_style_text_color(ui_SN3LAB10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3LAB11 = lv_label_create(ui_SN3IM1);
    lv_obj_set_width(ui_SN3LAB11, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB11, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB11, 70);
    lv_obj_set_y(ui_SN3LAB11, 0);
    lv_obj_set_align(ui_SN3LAB11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB11, Version_String_Buff);
    lv_obj_set_style_text_color(ui_SN3LAB11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3IM4 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_SN3IM4, &ui_img_tg_logo_rgb_128_png);
    lv_obj_set_width(ui_SN3IM4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3IM4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3IM4, 140);
    lv_obj_set_y(ui_SN3IM4, 350);
    lv_obj_set_align(ui_SN3IM4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3IM4, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3IM4, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3LAB12 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_SN3LAB12, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3LAB12, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3LAB12, -140);
    lv_obj_set_y(ui_SN3LAB12, 360);
    lv_obj_set_align(ui_SN3LAB12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3LAB12, my_nvs_Get_Device_ID());
    lv_obj_set_style_text_color(ui_SN3LAB12, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3LAB12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3LAB12, &ui_font_HEI18X4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_SN3PNL1, 480);
    lv_obj_set_height(ui_SN3PNL1, 800);
    lv_obj_set_x(ui_SN3PNL1, 0);
    lv_obj_set_y(ui_SN3PNL1, 0);
    lv_obj_set_align(ui_SN3PNL1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SN3PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN3PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN3PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN3PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN3PNL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL1LAB1 = lv_label_create(ui_SN3PNL1);
    lv_obj_set_width(ui_SN3PNL1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL1LAB1, 0);
    lv_obj_set_y(ui_SN3PNL1LAB1, -150);
    lv_obj_set_align(ui_SN3PNL1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL1LAB1, "設置");
    lv_obj_set_style_text_color(ui_SN3PNL1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL1LAB1, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL1IM1 = lv_img_create(ui_SN3PNL1);
    lv_img_set_src(ui_SN3PNL1IM1, &ui_img_682500442);
    lv_obj_set_width(ui_SN3PNL1IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL1IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL1IM1, -220);
    lv_obj_set_y(ui_SN3PNL1IM1, -290);
    lv_obj_set_align(ui_SN3PNL1IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL1IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL1IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL1BTN1 = lv_btn_create(ui_SN3PNL1);
    lv_obj_set_width(ui_SN3PNL1BTN1, 160);
    lv_obj_set_height(ui_SN3PNL1BTN1, 35);
    lv_obj_set_x(ui_SN3PNL1BTN1, -130);
    lv_obj_set_y(ui_SN3PNL1BTN1, -290);
    lv_obj_set_align(ui_SN3PNL1BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL1BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL1BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL1BTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL1BTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN3PNL1BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN3PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL1BTN1LAB1 = lv_label_create(ui_SN3PNL1BTN1);
    lv_obj_set_width(ui_SN3PNL1BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL1BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL1BTN1LAB1, -4);
    lv_obj_set_y(ui_SN3PNL1BTN1LAB1, 0);
    lv_obj_set_align(ui_SN3PNL1BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL1BTN1LAB1, "返回主目錄"); //
    lv_obj_set_style_text_color(ui_SN3PNL1BTN1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL1BTN1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL1BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL1BTN2 = lv_btn_create(ui_SN3PNL1);
    lv_obj_set_width(ui_SN3PNL1BTN2, 385);
    lv_obj_set_height(ui_SN3PNL1BTN2, 76);
    lv_obj_set_x(ui_SN3PNL1BTN2, 0);
    lv_obj_set_y(ui_SN3PNL1BTN2, 100);
    lv_obj_set_align(ui_SN3PNL1BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL1BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL1BTN2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL1BTN2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL1BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL1BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL1BTN2IM1 = lv_img_create(ui_SN3PNL1BTN2);
    lv_img_set_src(ui_SN3PNL1BTN2IM1, &ui_img_1095490412);
    lv_obj_set_width(ui_SN3PNL1BTN2IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL1BTN2IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL1BTN2IM1, -143);
    lv_obj_set_y(ui_SN3PNL1BTN2IM1, 5);
    lv_obj_set_align(ui_SN3PNL1BTN2IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL1BTN2IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL1BTN2IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL1BTN2IM2 = lv_img_create(ui_SN3PNL1BTN2);
    lv_img_set_src(ui_SN3PNL1BTN2IM2, &ui_img_2017929843);
    lv_obj_set_width(ui_SN3PNL1BTN2IM2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL1BTN2IM2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL1BTN2IM2, 106);
    lv_obj_set_y(ui_SN3PNL1BTN2IM2, 2);
    lv_obj_set_align(ui_SN3PNL1BTN2IM2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL1BTN2IM2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL1BTN2IM2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL1BTN2LAB1 = lv_label_create(ui_SN3PNL1BTN2);
    lv_obj_set_width(ui_SN3PNL1BTN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL1BTN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL1BTN2LAB1, -32);
    lv_obj_set_y(ui_SN3PNL1BTN2LAB1, 4);
    lv_obj_set_align(ui_SN3PNL1BTN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL1BTN2LAB1, "數據紀錄");
    lv_obj_set_style_text_font(ui_SN3PNL1BTN2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL1BTN3 = lv_btn_create(ui_SN3PNL1);
    lv_obj_set_width(ui_SN3PNL1BTN3, 385);
    lv_obj_set_height(ui_SN3PNL1BTN3, 76);
    lv_obj_set_x(ui_SN3PNL1BTN3, 0);
    lv_obj_set_y(ui_SN3PNL1BTN3, -30);
    lv_obj_set_align(ui_SN3PNL1BTN3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL1BTN3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL1BTN3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL1BTN3, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL1BTN3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL1BTN3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL1BTN3IM1 = lv_img_create(ui_SN3PNL1BTN3);
    lv_img_set_src(ui_SN3PNL1BTN3IM1, &ui_img_1651982571);
    lv_obj_set_width(ui_SN3PNL1BTN3IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL1BTN3IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL1BTN3IM1, -143);
    lv_obj_set_y(ui_SN3PNL1BTN3IM1, 1);
    lv_obj_set_align(ui_SN3PNL1BTN3IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL1BTN3IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL1BTN3IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL1BTN3IM2 = lv_img_create(ui_SN3PNL1BTN3);
    lv_img_set_src(ui_SN3PNL1BTN3IM2, &ui_img_2017929843);
    lv_obj_set_width(ui_SN3PNL1BTN3IM2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL1BTN3IM2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL1BTN3IM2, 119);
    lv_obj_set_y(ui_SN3PNL1BTN3IM2, 1);
    lv_obj_set_align(ui_SN3PNL1BTN3IM2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL1BTN3IM2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL1BTN3IM2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL1BTN3LAB1 = lv_label_create(ui_SN3PNL1BTN3);
    lv_obj_set_width(ui_SN3PNL1BTN3LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL1BTN3LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL1BTN3LAB1, -20);
    lv_obj_set_y(ui_SN3PNL1BTN3LAB1, 0);
    lv_obj_set_align(ui_SN3PNL1BTN3LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL1BTN3LAB1, "參數設置");
    lv_obj_set_style_text_font(ui_SN3PNL1BTN3LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_SN3PNL2, 480);
    lv_obj_set_height(ui_SN3PNL2, 800);
    lv_obj_set_x(ui_SN3PNL2, 0);
    lv_obj_set_y(ui_SN3PNL2, 0);
    lv_obj_set_align(ui_SN3PNL2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL2, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN3PNL2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN3PNL2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN3PNL2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN3PNL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN3PNL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL2LAB1 = lv_label_create(ui_SN3PNL2);
    lv_obj_set_width(ui_SN3PNL2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL2LAB1, 0);
    lv_obj_set_y(ui_SN3PNL2LAB1, -150);
    lv_obj_set_align(ui_SN3PNL2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL2LAB1, "數據紀錄");
    lv_obj_set_style_text_color(ui_SN3PNL2LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL2LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL2LAB1, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL2IM1 = lv_img_create(ui_SN3PNL2);
    lv_img_set_src(ui_SN3PNL2IM1, &ui_img_682500442);
    lv_obj_set_width(ui_SN3PNL2IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL2IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL2IM1, -220);
    lv_obj_set_y(ui_SN3PNL2IM1, -290);
    lv_obj_set_align(ui_SN3PNL2IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL2IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL2IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL2BTN1 = lv_btn_create(ui_SN3PNL2);
    lv_obj_set_width(ui_SN3PNL2BTN1, 80);
    lv_obj_set_height(ui_SN3PNL2BTN1, 35);
    lv_obj_set_x(ui_SN3PNL2BTN1, -170);
    lv_obj_set_y(ui_SN3PNL2BTN1, -290);
    lv_obj_set_align(ui_SN3PNL2BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL2BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL2BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL2BTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL2BTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL2BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN3PNL2BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN3PNL2BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL2BTN1LAB1 = lv_label_create(ui_SN3PNL2BTN1);
    lv_obj_set_width(ui_SN3PNL2BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL2BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL2BTN1LAB1, -4);
    lv_obj_set_y(ui_SN3PNL2BTN1LAB1, 0);
    lv_obj_set_align(ui_SN3PNL2BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL2BTN1LAB1, "返回");
    lv_obj_set_style_text_color(ui_SN3PNL2BTN1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL2BTN1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL2BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL2BTN2 = lv_btn_create(ui_SN3PNL2);
    lv_obj_set_width(ui_SN3PNL2BTN2, 385);
    lv_obj_set_height(ui_SN3PNL2BTN2, 76);
    lv_obj_set_x(ui_SN3PNL2BTN2, 0);
    lv_obj_set_y(ui_SN3PNL2BTN2, 100);
    lv_obj_set_align(ui_SN3PNL2BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL2BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL2BTN2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL2BTN2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL2BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL2BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL2BTN2IM1 = lv_img_create(ui_SN3PNL2BTN2);
    lv_img_set_src(ui_SN3PNL2BTN2IM1, &ui_img_690220074);
    lv_obj_set_width(ui_SN3PNL2BTN2IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL2BTN2IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL2BTN2IM1, -143);
    lv_obj_set_y(ui_SN3PNL2BTN2IM1, 5);
    lv_obj_set_align(ui_SN3PNL2BTN2IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL2BTN2IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL2BTN2IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL2BTN2IM2 = lv_img_create(ui_SN3PNL2BTN2);
    lv_img_set_src(ui_SN3PNL2BTN2IM2, &ui_img_2017929843);
    lv_obj_set_width(ui_SN3PNL2BTN2IM2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL2BTN2IM2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL2BTN2IM2, 114);
    lv_obj_set_y(ui_SN3PNL2BTN2IM2, 2);
    lv_obj_set_align(ui_SN3PNL2BTN2IM2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL2BTN2IM2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL2BTN2IM2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL2BTN2LAB1 = lv_label_create(ui_SN3PNL2BTN2);
    lv_obj_set_width(ui_SN3PNL2BTN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL2BTN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL2BTN2LAB1, -19);
    lv_obj_set_y(ui_SN3PNL2BTN2LAB1, 3);
    lv_obj_set_align(ui_SN3PNL2BTN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL2BTN2LAB1, "軟件升級");
    lv_obj_set_style_text_font(ui_SN3PNL2BTN2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL2BTN3 = lv_btn_create(ui_SN3PNL2);
    lv_obj_set_width(ui_SN3PNL2BTN3, 385);
    lv_obj_set_height(ui_SN3PNL2BTN3, 76);
    lv_obj_set_x(ui_SN3PNL2BTN3, 0);
    lv_obj_set_y(ui_SN3PNL2BTN3, -30);
    lv_obj_set_align(ui_SN3PNL2BTN3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL2BTN3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL2BTN3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL2BTN3, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL2BTN3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL2BTN3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL2BTN3IM1 = lv_img_create(ui_SN3PNL2BTN3);
    lv_img_set_src(ui_SN3PNL2BTN3IM1, &ui_img_439061707);
    lv_obj_set_width(ui_SN3PNL2BTN3IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL2BTN3IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL2BTN3IM1, -143);
    lv_obj_set_y(ui_SN3PNL2BTN3IM1, 1);
    lv_obj_set_align(ui_SN3PNL2BTN3IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL2BTN3IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL2BTN3IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL2BTN3IM2 = lv_img_create(ui_SN3PNL2BTN3);
    lv_img_set_src(ui_SN3PNL2BTN3IM2, &ui_img_2017929843);
    lv_obj_set_width(ui_SN3PNL2BTN3IM2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL2BTN3IM2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL2BTN3IM2, 119);
    lv_obj_set_y(ui_SN3PNL2BTN3IM2, 1);
    lv_obj_set_align(ui_SN3PNL2BTN3IM2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL2BTN3IM2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL2BTN3IM2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL2BTN3LAB1 = lv_label_create(ui_SN3PNL2BTN3);
    lv_obj_set_width(ui_SN3PNL2BTN3LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL2BTN3LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL2BTN3LAB1, -20);
    lv_obj_set_y(ui_SN3PNL2BTN3LAB1, 0);
    lv_obj_set_align(ui_SN3PNL2BTN3LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL2BTN3LAB1, "USB掛載");
    lv_obj_set_style_text_font(ui_SN3PNL2BTN3LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_SN3PNL3, 480);
    lv_obj_set_height(ui_SN3PNL3, 800);
    lv_obj_set_x(ui_SN3PNL3, 0);
    lv_obj_set_y(ui_SN3PNL3, 0);
    lv_obj_set_align(ui_SN3PNL3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL3, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN3PNL3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN3PNL3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN3PNL3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN3PNL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN3PNL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3LAB1 = lv_label_create(ui_SN3PNL3);
    lv_obj_set_width(ui_SN3PNL3LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL3LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL3LAB1, -3);
    lv_obj_set_y(ui_SN3PNL3LAB1, -147);
    lv_obj_set_align(ui_SN3PNL3LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL3LAB1, "USB掛載");
    lv_obj_set_style_text_color(ui_SN3PNL3LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL3LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL3LAB1, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL1 = lv_obj_create(ui_SN3PNL3);
    lv_obj_set_width(ui_SN3PNL3PNL1, 410);
    lv_obj_set_height(ui_SN3PNL3PNL1, 225);
    lv_obj_set_x(ui_SN3PNL3PNL1, 0);
    lv_obj_set_y(ui_SN3PNL3PNL1, 55);
    lv_obj_set_align(ui_SN3PNL3PNL1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SN3PNL3PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_SN3PNL3PNL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL3PNL1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL3PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN3PNL3PNL1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN3PNL3PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN3PNL3PNL1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL1LAB1 = lv_label_create(ui_SN3PNL3PNL1);
    lv_obj_set_width(ui_SN3PNL3PNL1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL3PNL1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL3PNL1LAB1, 0);
    lv_obj_set_y(ui_SN3PNL3PNL1LAB1, -50);
    lv_obj_set_align(ui_SN3PNL3PNL1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL3PNL1LAB1, "導出資料中...");
    lv_obj_set_style_text_color(ui_SN3PNL3PNL1LAB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL3PNL1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL3PNL1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL1LAB2 = lv_label_create(ui_SN3PNL3PNL1);
    lv_obj_set_width(ui_SN3PNL3PNL1LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL3PNL1LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL3PNL1LAB2, 0);
    lv_obj_set_y(ui_SN3PNL3PNL1LAB2, -10);
    lv_obj_set_align(ui_SN3PNL3PNL1LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL3PNL1LAB2, "請勿隨意關機");
    lv_obj_set_style_text_color(ui_SN3PNL3PNL1LAB2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL3PNL1LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL3PNL1LAB2, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL1BTN1 = lv_btn_create(ui_SN3PNL3PNL1);
    lv_obj_set_width(ui_SN3PNL3PNL1BTN1, 73);
    lv_obj_set_height(ui_SN3PNL3PNL1BTN1, 36);
    lv_obj_set_x(ui_SN3PNL3PNL1BTN1, 0);
    lv_obj_set_y(ui_SN3PNL3PNL1BTN1, 50);
    lv_obj_set_align(ui_SN3PNL3PNL1BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL3PNL1BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL3PNL1BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL3PNL1BTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL3PNL1BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL3PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN3PNL3PNL1BTN1, lv_color_hex(0xF00000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN3PNL3PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL1BTN1LAB1 = lv_label_create(ui_SN3PNL3PNL1BTN1);
    lv_obj_set_width(ui_SN3PNL3PNL1BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL3PNL1BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN3PNL3PNL1BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL3PNL1BTN1LAB1, "退出");
    lv_obj_set_style_text_color(ui_SN3PNL3PNL1BTN1LAB1, lv_color_hex(0xF00000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL3PNL1BTN1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL3PNL1BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL2 = lv_obj_create(ui_SN3PNL3);
    lv_obj_set_width(ui_SN3PNL3PNL2, 410);
    lv_obj_set_height(ui_SN3PNL3PNL2, 225);
    lv_obj_set_x(ui_SN3PNL3PNL2, 0);
    lv_obj_set_y(ui_SN3PNL3PNL2, 55);
    lv_obj_set_align(ui_SN3PNL3PNL2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL3PNL2, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN3PNL3PNL2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_SN3PNL3PNL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL3PNL2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL3PNL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN3PNL3PNL2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN3PNL3PNL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN3PNL3PNL2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL2LAB1 = lv_label_create(ui_SN3PNL3PNL2);
    lv_obj_set_width(ui_SN3PNL3PNL2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL3PNL2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL3PNL2LAB1, 1);
    lv_obj_set_y(ui_SN3PNL3PNL2LAB1, -68);
    lv_obj_set_align(ui_SN3PNL3PNL2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL3PNL2LAB1, "!資料導出中!");
    lv_obj_set_style_text_color(ui_SN3PNL3PNL2LAB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL3PNL2LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL3PNL2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL2LAB2 = lv_label_create(ui_SN3PNL3PNL2);
    lv_obj_set_width(ui_SN3PNL3PNL2LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL3PNL2LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL3PNL2LAB2, 0);
    lv_obj_set_y(ui_SN3PNL3PNL2LAB2, -29);
    lv_obj_set_align(ui_SN3PNL3PNL2LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL3PNL2LAB2, "如中途退出");
    lv_obj_set_style_text_color(ui_SN3PNL3PNL2LAB2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL3PNL2LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL3PNL2LAB2, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL2LAB3 = lv_label_create(ui_SN3PNL3PNL2);
    lv_obj_set_width(ui_SN3PNL3PNL2LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL3PNL2LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL3PNL2LAB3, 0);
    lv_obj_set_y(ui_SN3PNL3PNL2LAB3, 14);
    lv_obj_set_align(ui_SN3PNL3PNL2LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL3PNL2LAB3, "可能會導致資料損失.");
    lv_obj_set_style_text_color(ui_SN3PNL3PNL2LAB3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL3PNL2LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL3PNL2LAB3, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL2BTN1 = lv_btn_create(ui_SN3PNL3PNL2);
    lv_obj_set_width(ui_SN3PNL3PNL2BTN1, 120);
    lv_obj_set_height(ui_SN3PNL3PNL2BTN1, 36);
    lv_obj_set_x(ui_SN3PNL3PNL2BTN1, -1);
    lv_obj_set_y(ui_SN3PNL3PNL2BTN1, 57);
    lv_obj_set_align(ui_SN3PNL3PNL2BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL3PNL2BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL3PNL2BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL3PNL2BTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL3PNL2BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL3PNL2BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN3PNL3PNL2BTN1, lv_color_hex(0xF00000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN3PNL3PNL2BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL3PNL2BTN1LAB1 = lv_label_create(ui_SN3PNL3PNL2BTN1);
    lv_obj_set_width(ui_SN3PNL3PNL2BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL3PNL2BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN3PNL3PNL2BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL3PNL2BTN1LAB1, "確認退出");
    lv_obj_set_style_text_color(ui_SN3PNL3PNL2BTN1LAB1, lv_color_hex(0xF00000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL3PNL2BTN1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL3PNL2BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_SN3PNL4, 480);
    lv_obj_set_height(ui_SN3PNL4, 800);
    lv_obj_set_x(ui_SN3PNL4, 0);
    lv_obj_set_y(ui_SN3PNL4, 0);
    lv_obj_set_align(ui_SN3PNL4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL4, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN3PNL4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN3PNL4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN3PNL4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN3PNL4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN3PNL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4IM1 = lv_img_create(ui_SN3PNL4);
    lv_img_set_src(ui_SN3PNL4IM1, &ui_img_682500442);
    lv_obj_set_width(ui_SN3PNL4IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL4IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL4IM1, -220);
    lv_obj_set_y(ui_SN3PNL4IM1, -290);
    lv_obj_set_align(ui_SN3PNL4IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL4IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL4IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL4LAB1 = lv_label_create(ui_SN3PNL4);
    lv_obj_set_width(ui_SN3PNL4LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL4LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL4LAB1, -10);
    lv_obj_set_y(ui_SN3PNL4LAB1, -80);
    lv_obj_set_align(ui_SN3PNL4LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL4LAB1, "firmware_name");
    lv_obj_set_style_text_color(ui_SN3PNL4LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL4LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL4LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4LAB2 = lv_label_create(ui_SN3PNL4);
    lv_obj_set_width(ui_SN3PNL4LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL4LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL4LAB2, -70);
    lv_obj_set_y(ui_SN3PNL4LAB2, 0);
    lv_obj_set_align(ui_SN3PNL4LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL4LAB2, Version_String_Buff);
    lv_obj_set_style_text_color(ui_SN3PNL4LAB2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL4LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL4LAB2, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4LAB3 = lv_label_create(ui_SN3PNL4);
    lv_obj_set_width(ui_SN3PNL4LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL4LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN3PNL4LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL4LAB3, "->");
    lv_obj_set_style_text_color(ui_SN3PNL4LAB3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL4LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL4LAB3, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4LAB4 = lv_label_create(ui_SN3PNL4);
    lv_obj_set_width(ui_SN3PNL4LAB4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL4LAB4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL4LAB4, 70);
    lv_obj_set_y(ui_SN3PNL4LAB4, 0);
    lv_obj_set_align(ui_SN3PNL4LAB4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL4LAB4, "V2.00");
    lv_obj_set_style_text_color(ui_SN3PNL4LAB4, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL4LAB4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL4LAB4, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4LAB5 = lv_label_create(ui_SN3PNL4);
    lv_obj_set_width(ui_SN3PNL4LAB5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL4LAB5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL4LAB5, -10);
    lv_obj_set_y(ui_SN3PNL4LAB5, -185);
    lv_obj_set_align(ui_SN3PNL4LAB5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL4LAB5, "軟件升級");
    lv_obj_set_style_text_color(ui_SN3PNL4LAB5, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL4LAB5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL4LAB5, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4LAB6 = lv_label_create(ui_SN3PNL4);
    lv_obj_set_width(ui_SN3PNL4LAB6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL4LAB6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL4LAB6, 175);
    lv_obj_set_y(ui_SN3PNL4LAB6, 111);
    lv_obj_set_align(ui_SN3PNL4LAB6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL4LAB6, "0");
    lv_obj_set_style_text_color(ui_SN3PNL4LAB6, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL4LAB6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL4LAB6, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4LAB7 = lv_label_create(ui_SN3PNL4);
    lv_obj_set_width(ui_SN3PNL4LAB7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL4LAB7, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL4LAB7, 211);
    lv_obj_set_y(ui_SN3PNL4LAB7, 110);
    lv_obj_set_align(ui_SN3PNL4LAB7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL4LAB7, "%");
    lv_obj_set_style_text_color(ui_SN3PNL4LAB7, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL4LAB7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL4LAB7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4BAR1 = lv_bar_create(ui_SN3PNL4);
    lv_obj_set_width(ui_SN3PNL4BAR1, 361);
    lv_obj_set_height(ui_SN3PNL4BAR1, 29);
    lv_obj_set_x(ui_SN3PNL4BAR1, -36);
    lv_obj_set_y(ui_SN3PNL4BAR1, 112);
    lv_obj_set_align(ui_SN3PNL4BAR1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SN3PNL4BAR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL4BAR1, lv_color_hex(0x808991), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL4BAR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SN3PNL4BAR1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL4BAR1, lv_color_hex(0x17FC1F), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL4BAR1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SN3PNL4BTN1 = lv_btn_create(ui_SN3PNL4);
    lv_obj_set_width(ui_SN3PNL4BTN1, 80);
    lv_obj_set_height(ui_SN3PNL4BTN1, 35);
    lv_obj_set_x(ui_SN3PNL4BTN1, -170);
    lv_obj_set_y(ui_SN3PNL4BTN1, -290);
    lv_obj_set_align(ui_SN3PNL4BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL4BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL4BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL4BTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL4BTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL4BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN3PNL4BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN3PNL4BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4BTN1LAB1 = lv_label_create(ui_SN3PNL4BTN1);
    lv_obj_set_width(ui_SN3PNL4BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL4BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL4BTN1LAB1, -4);
    lv_obj_set_y(ui_SN3PNL4BTN1LAB1, 0);
    lv_obj_set_align(ui_SN3PNL4BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL4BTN1LAB1, "返回");
    lv_obj_set_style_text_color(ui_SN3PNL4BTN1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL4BTN1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL4BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4BTN2 = lv_btn_create(ui_SN3PNL4);
    lv_obj_set_width(ui_SN3PNL4BTN2, 220);
    lv_obj_set_height(ui_SN3PNL4BTN2, 76);
    lv_obj_set_x(ui_SN3PNL4BTN2, -1);
    lv_obj_set_y(ui_SN3PNL4BTN2, 240);
    lv_obj_set_align(ui_SN3PNL4BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL4BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL4BTN2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_SN3PNL4BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL4BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL4BTN2LAB1 = lv_label_create(ui_SN3PNL4BTN2);
    lv_obj_set_width(ui_SN3PNL4BTN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL4BTN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN3PNL4BTN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL4BTN2LAB1, "升級");
    lv_obj_set_style_text_color(ui_SN3PNL4BTN2LAB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL4BTN2LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL4BTN2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL5 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_SN3PNL5, 480);
    lv_obj_set_height(ui_SN3PNL5, 800);
    lv_obj_set_x(ui_SN3PNL5, 0);
    lv_obj_set_y(ui_SN3PNL5, 0);
    lv_obj_set_align(ui_SN3PNL5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL5, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN3PNL5, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN3PNL5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN3PNL5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN3PNL5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN3PNL5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL5LAB1 = lv_label_create(ui_SN3PNL5);
    lv_obj_set_width(ui_SN3PNL5LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL5LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL5LAB1, -130);
    lv_obj_set_y(ui_SN3PNL5LAB1, -50);
    lv_obj_set_align(ui_SN3PNL5LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL5LAB1, "管理員密碼:");
    lv_obj_set_style_text_color(ui_SN3PNL5LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL5LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL5LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL5LAB2 = lv_label_create(ui_SN3PNL5);
    lv_obj_set_width(ui_SN3PNL5LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL5LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL5LAB2, 88);
    lv_obj_set_y(ui_SN3PNL5LAB2, -2);
    lv_obj_set_align(ui_SN3PNL5LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL5LAB2, "*密碼錯誤,請重新輸入.");
    lv_obj_add_flag(ui_SN3PNL5LAB2, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN3PNL5LAB2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL5LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL5LAB2, &ui_font_HEI22x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL5LAB3 = lv_label_create(ui_SN3PNL5);
    lv_obj_set_width(ui_SN3PNL5LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL5LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL5LAB3, 0);
    lv_obj_set_y(ui_SN3PNL5LAB3, -150);
    lv_obj_set_align(ui_SN3PNL5LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL5LAB3, "參數設置");
    lv_obj_set_style_text_color(ui_SN3PNL5LAB3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL5LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL5LAB3, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL5IM1 = lv_img_create(ui_SN3PNL5);
    lv_img_set_src(ui_SN3PNL5IM1, &ui_img_682500442);
    lv_obj_set_width(ui_SN3PNL5IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL5IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL5IM1, -220);
    lv_obj_set_y(ui_SN3PNL5IM1, -290);
    lv_obj_set_align(ui_SN3PNL5IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL5IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN3PNL5IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN3PNL5TXT1 = lv_textarea_create(ui_SN3PNL5);
    lv_obj_set_width(ui_SN3PNL5TXT1, 228);
    lv_obj_set_height(ui_SN3PNL5TXT1, LV_SIZE_CONTENT); /// 38
    lv_obj_set_x(ui_SN3PNL5TXT1, 90);
    lv_obj_set_y(ui_SN3PNL5TXT1, -55);
    lv_obj_set_align(ui_SN3PNL5TXT1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SN3PNL5TXT1, "請輸入密碼(123456)");
    lv_textarea_set_max_length(ui_SN3PNL5TXT1, 8);
    lv_textarea_set_one_line(ui_SN3PNL5TXT1, true);
    lv_obj_set_style_text_color(ui_SN3PNL5TXT1, lv_color_hex(0x808991), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL5TXT1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL5TXT1, &ui_font_HEI22x4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SN3PNL5TXT1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN3PNL5TXT1, lv_color_hex(0x808991), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN3PNL5TXT1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SN3PNL5TXT1, lv_color_hex(0x808991), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL5TXT1, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SN3PNL5TXT1, lv_color_hex(0x808991), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL5TXT1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_SN3PNL5BTN1 = lv_btn_create(ui_SN3PNL5);
    lv_obj_set_width(ui_SN3PNL5BTN1, 80);
    lv_obj_set_height(ui_SN3PNL5BTN1, 35);
    lv_obj_set_x(ui_SN3PNL5BTN1, -170);
    lv_obj_set_y(ui_SN3PNL5BTN1, -290);
    lv_obj_set_align(ui_SN3PNL5BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL5BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL5BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL5BTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL5BTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL5BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN3PNL5BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN3PNL5BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL5BTN1LAB1 = lv_label_create(ui_SN3PNL5BTN1);
    lv_obj_set_width(ui_SN3PNL5BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL5BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL5BTN1LAB1, -4);
    lv_obj_set_y(ui_SN3PNL5BTN1LAB1, 0);
    lv_obj_set_align(ui_SN3PNL5BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL5BTN1LAB1, "返回");
    lv_obj_set_style_text_color(ui_SN3PNL5BTN1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL5BTN1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL5BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL5BTN2 = lv_btn_create(ui_SN3PNL5);
    lv_obj_set_width(ui_SN3PNL5BTN2, 220);
    lv_obj_set_height(ui_SN3PNL5BTN2, 76);
    lv_obj_set_x(ui_SN3PNL5BTN2, 0);
    lv_obj_set_y(ui_SN3PNL5BTN2, 60);
    lv_obj_set_align(ui_SN3PNL5BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL5BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL5BTN2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL5BTN2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL5BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL5BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL5BTN2LAB1 = lv_label_create(ui_SN3PNL5BTN2);
    lv_obj_set_width(ui_SN3PNL5BTN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL5BTN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL5BTN2LAB1, -8);
    lv_obj_set_y(ui_SN3PNL5BTN2LAB1, 2);
    lv_obj_set_align(ui_SN3PNL5BTN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL5BTN2LAB1, "登入");
    lv_obj_set_style_text_font(ui_SN3PNL5BTN2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL5BTN3 = lv_btn_create(ui_SN3PNL5);
    lv_obj_set_width(ui_SN3PNL5BTN3, 170);
    lv_obj_set_height(ui_SN3PNL5BTN3, 50);
    lv_obj_set_x(ui_SN3PNL5BTN3, 0);
    lv_obj_set_y(ui_SN3PNL5BTN3, 220);
    lv_obj_set_align(ui_SN3PNL5BTN3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL5BTN3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL5BTN3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL5BTN3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL5BTN3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL5BTN3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN3PNL5BTN3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN3PNL5BTN3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SN3PNL5BTN3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL5BTN3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL5BTN3LAB1 = lv_label_create(ui_SN3PNL5BTN3);
    lv_obj_set_width(ui_SN3PNL5BTN3LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL5BTN3LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL5BTN3LAB1, 0);
    lv_obj_set_y(ui_SN3PNL5BTN3LAB1, 7);
    lv_obj_set_align(ui_SN3PNL5BTN3LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL5BTN3LAB1, "無密碼登入");
    lv_obj_set_style_text_font(ui_SN3PNL5BTN3LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN3PNL6 = lv_obj_create(ui_Screen3);
    // lv_obj_set_width(ui_SN3PNL6, 480);
    // lv_obj_set_height(ui_SN3PNL6, 800);
    // lv_obj_set_align(ui_SN3PNL6, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN3PNL6, LV_OBJ_FLAG_HIDDEN);       /// Flags
    // lv_obj_clear_flag(ui_SN3PNL6, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    // lv_obj_set_style_radius(ui_SN3PNL6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_SN3PNL6, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_SN3PNL6, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN3PNL6PNL1 = lv_obj_create(ui_SN3PNL6);
    // lv_obj_set_width(ui_SN3PNL6PNL1, 420);
    // lv_obj_set_height(ui_SN3PNL6PNL1, 260);
    // lv_obj_set_x(ui_SN3PNL6PNL1, 0);
    // lv_obj_set_y(ui_SN3PNL6PNL1, -30);
    // lv_obj_set_align(ui_SN3PNL6PNL1, LV_ALIGN_CENTER);
    // lv_obj_clear_flag(ui_SN3PNL6PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    // lv_obj_set_style_bg_color(ui_SN3PNL6PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_SN3PNL6PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_color(ui_SN3PNL6PNL1, lv_color_hex(0x06FC41), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_opa(ui_SN3PNL6PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_width(ui_SN3PNL6PNL1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN3PNL6PNL1BTN1 = lv_btn_create(ui_SN3PNL6PNL1);
    // lv_obj_set_width(ui_SN3PNL6PNL1BTN1, 120);
    // lv_obj_set_height(ui_SN3PNL6PNL1BTN1, 70);
    // lv_obj_set_x(ui_SN3PNL6PNL1BTN1, 0);
    // lv_obj_set_y(ui_SN3PNL6PNL1BTN1, 60);
    // lv_obj_set_align(ui_SN3PNL6PNL1BTN1, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN3PNL6PNL1BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    // lv_obj_clear_flag(ui_SN3PNL6PNL1BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    // lv_obj_set_style_radius(ui_SN3PNL6PNL1BTN1, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_SN3PNL6PNL1BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_SN3PNL6PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN6PNL11PNL1BTN1LAB3 = lv_label_create(ui_SN3PNL6PNL1BTN1);
    // lv_obj_set_width(ui_SN6PNL11PNL1BTN1LAB3, LV_SIZE_CONTENT);  /// 1
    // lv_obj_set_height(ui_SN6PNL11PNL1BTN1LAB3, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_align(ui_SN6PNL11PNL1BTN1LAB3, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_SN6PNL11PNL1BTN1LAB3, "確認");
    // lv_obj_set_style_text_font(ui_SN6PNL11PNL1BTN1LAB3, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN3PNL6PNL1LAB1 = lv_label_create(ui_SN3PNL6PNL1);
    // lv_obj_set_width(ui_SN3PNL6PNL1LAB1, LV_SIZE_CONTENT);  /// 1
    // lv_obj_set_height(ui_SN3PNL6PNL1LAB1, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_SN3PNL6PNL1LAB1, 0);
    // lv_obj_set_y(ui_SN3PNL6PNL1LAB1, -50);
    // lv_obj_set_align(ui_SN3PNL6PNL1LAB1, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_SN3PNL6PNL1LAB1, "是否確認關機");
    // lv_obj_set_style_text_color(ui_SN3PNL6PNL1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_SN3PNL6PNL1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_SN3PNL6PNL1LAB1, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL6 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_SN3PNL6, 486);
    lv_obj_set_height(ui_SN3PNL6, 806);
    lv_obj_set_align(ui_SN3PNL6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL6, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN3PNL6, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_SN3PNL6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL6, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL6PNL1 = lv_obj_create(ui_SN3PNL6);
    lv_obj_set_width(ui_SN3PNL6PNL1, 420);
    lv_obj_set_height(ui_SN3PNL6PNL1, 260);
    lv_obj_set_x(ui_SN3PNL6PNL1, 0);
    lv_obj_set_y(ui_SN3PNL6PNL1, -30);
    lv_obj_set_align(ui_SN3PNL6PNL1, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN3PNL6PNL1, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN3PNL6PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN3PNL6PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL6PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN3PNL6PNL1, lv_color_hex(0x06FC41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN3PNL6PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN3PNL6PNL1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL6PNL1BTN1 = lv_btn_create(ui_SN3PNL6PNL1);
    lv_obj_set_width(ui_SN3PNL6PNL1BTN1, 120);
    lv_obj_set_height(ui_SN3PNL6PNL1BTN1, 70);
    lv_obj_set_x(ui_SN3PNL6PNL1BTN1, -85);
    lv_obj_set_y(ui_SN3PNL6PNL1BTN1, 60);
    lv_obj_set_align(ui_SN3PNL6PNL1BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL6PNL1BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL6PNL1BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL6PNL1BTN1, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL6PNL1BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL6PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL11PNL1BTN1LAB3 = lv_label_create(ui_SN3PNL6PNL1BTN1);
    lv_obj_set_width(ui_SN6PNL11PNL1BTN1LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL11PNL1BTN1LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL11PNL1BTN1LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL11PNL1BTN1LAB3, "確認");
    lv_obj_set_style_text_font(ui_SN6PNL11PNL1BTN1LAB3, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL6PNL1LAB1 = lv_label_create(ui_SN3PNL6PNL1);
    lv_obj_set_width(ui_SN3PNL6PNL1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL6PNL1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN3PNL6PNL1LAB1, 0);
    lv_obj_set_y(ui_SN3PNL6PNL1LAB1, -50);
    lv_obj_set_align(ui_SN3PNL6PNL1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL6PNL1LAB1, "是否確認關機");
    lv_obj_set_style_text_color(ui_SN3PNL6PNL1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN3PNL6PNL1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN3PNL6PNL1LAB1, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_SN3PNL6PNL1BTN2 = lv_btn_create(ui_SN3PNL6PNL1);
    lv_obj_set_width(ui_SN3PNL6PNL1BTN2, 120);
    lv_obj_set_height(ui_SN3PNL6PNL1BTN2, 70);
    lv_obj_set_x(ui_SN3PNL6PNL1BTN2, 85);
    lv_obj_set_y(ui_SN3PNL6PNL1BTN2, 60);
    lv_obj_set_align(ui_SN3PNL6PNL1BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3PNL6PNL1BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN3PNL6PNL1BTN2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN3PNL6PNL1BTN2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN3PNL6PNL1BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3PNL6PNL1BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3PNL6PNL1BTN2LAB1 = lv_label_create(ui_SN3PNL6PNL1BTN2);
    lv_obj_set_width(ui_SN3PNL6PNL1BTN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN3PNL6PNL1BTN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN3PNL6PNL1BTN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN3PNL6PNL1BTN2LAB1, "取消");
    lv_obj_set_style_text_font(ui_SN3PNL6PNL1BTN2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN3KB1 = lv_keyboard_create(ui_Screen3);
    lv_keyboard_set_mode(ui_SN3KB1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_SN3KB1, 475);
    lv_obj_set_height(ui_SN3KB1, 330);
    lv_obj_set_x(ui_SN3KB1, 0);
    lv_obj_set_y(ui_SN3KB1, 230);
    lv_obj_set_align(ui_SN3KB1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN3KB1, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_bg_color(ui_SN3KB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN3KB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_SN3KB1, &lv_font_montserrat_32, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SN3PNL1BTN1, ui_event_SN3PNL1BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL1BTN2, ui_event_SN3PNL1BTN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL1BTN3, ui_event_SN3PNL1BTN3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL2BTN1, ui_event_SN3PNL2BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL2BTN2, ui_event_SN3PNL2BTN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL2BTN3, ui_event_SN3PNL2BTN3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL3PNL1BTN1, ui_event_SN3PNL3PNL1BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL3PNL2BTN1, ui_event_SN3PNL3PNL2BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL4BTN1, ui_event_SN3PNL4BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL4BTN2, ui_event_SN3PNL4BTN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL5TXT1, ui_event_SN3PNL5TXT1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL5BTN1, ui_event_SN3PNL5BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL5BTN2, ui_event_SN3PNL5BTN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL5BTN3LAB1, ui_event_SN3PNL5BTN3LAB1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL5BTN3, ui_event_SN3PNL5BTN3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL5, ui_event_SN3PNL5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3KB1, ui_event_SN3KB1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_SN3PNL6PNL1BTN1, ui_event_Shutdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN3PNL6PNL1BTN2, ui_event_Cancel, LV_EVENT_ALL, NULL);

    // ui_SN3PNL6 = lv_obj_create(ui_Screen3);
    // lv_obj_set_width(ui_SN3PNL6, 480);
    // lv_obj_set_height(ui_SN3PNL6, 800);
    // lv_obj_set_align(ui_SN3PNL6, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN3PNL6, LV_OBJ_FLAG_HIDDEN);       /// Flags
    // lv_obj_clear_flag(ui_SN3PNL6, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    // lv_obj_set_style_radius(ui_SN3PNL6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_SN3PNL6, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_SN3PNL6, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN3PNL6PNL1 = lv_obj_create(ui_SN3PNL6);
    // lv_obj_set_width(ui_SN3PNL6PNL1, 420);
    // lv_obj_set_height(ui_SN3PNL6PNL1, 260);
    // lv_obj_set_x(ui_SN3PNL6PNL1, 0);
    // lv_obj_set_y(ui_SN3PNL6PNL1, -30);
    // lv_obj_set_align(ui_SN3PNL6PNL1, LV_ALIGN_CENTER);
    // lv_obj_clear_flag(ui_SN3PNL6PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    // lv_obj_set_style_bg_color(ui_SN3PNL6PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_SN3PNL6PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_color(ui_SN3PNL6PNL1, lv_color_hex(0x06FC41), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_opa(ui_SN3PNL6PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_border_width(ui_SN3PNL6PNL1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN3PNL6PNL1BTN1 = lv_btn_create(ui_SN3PNL6PNL1);
    // lv_obj_set_width(ui_SN3PNL6PNL1BTN1, 120);
    // lv_obj_set_height(ui_SN3PNL6PNL1BTN1, 70);
    // lv_obj_set_x(ui_SN3PNL6PNL1BTN1, 0);
    // lv_obj_set_y(ui_SN3PNL6PNL1BTN1, 60);
    // lv_obj_set_align(ui_SN3PNL6PNL1BTN1, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN3PNL6PNL1BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    // lv_obj_clear_flag(ui_SN3PNL6PNL1BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    // lv_obj_set_style_radius(ui_SN3PNL6PNL1BTN1, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_color(ui_SN3PNL6PNL1BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_SN3PNL6PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN6PNL11PNL1BTN1LAB3 = lv_label_create(ui_SN3PNL6PNL1BTN1);
    // lv_obj_set_width(ui_SN6PNL11PNL1BTN1LAB3, LV_SIZE_CONTENT);  /// 1
    // lv_obj_set_height(ui_SN6PNL11PNL1BTN1LAB3, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_align(ui_SN6PNL11PNL1BTN1LAB3, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_SN6PNL11PNL1BTN1LAB3, "確認");
    // lv_obj_set_style_text_font(ui_SN6PNL11PNL1BTN1LAB3, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN3PNL6PNL1LAB1 = lv_label_create(ui_SN3PNL6PNL1);
    // lv_obj_set_width(ui_SN3PNL6PNL1LAB1, LV_SIZE_CONTENT);  /// 1
    // lv_obj_set_height(ui_SN3PNL6PNL1LAB1, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_SN3PNL6PNL1LAB1, 0);
    // lv_obj_set_y(ui_SN3PNL6PNL1LAB1, -50);
    // lv_obj_set_align(ui_SN3PNL6PNL1LAB1, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_SN3PNL6PNL1LAB1, "是否確認關機");
    // lv_obj_set_style_text_color(ui_SN3PNL6PNL1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_SN3PNL6PNL1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_SN3PNL6PNL1LAB1, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);
}
