// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: DZSJN

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6IM1 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_SN6IM1, &ui_img_rectangle_1_png);
    lv_obj_set_width(ui_SN6IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6IM1, 0);
    lv_obj_set_y(ui_SN6IM1, -365);
    lv_obj_set_align(ui_SN6IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN6IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // ui_SN6IM2 = lv_img_create(ui_Screen6);
    // lv_img_set_src(ui_SN6IM2, &ui_img_1551342831);
    // lv_obj_set_width(ui_SN6IM2, LV_SIZE_CONTENT);  /// 1
    // lv_obj_set_height(ui_SN6IM2, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_SN6IM2, 110);
    // lv_obj_set_y(ui_SN6IM2, -360);
    // lv_obj_set_align(ui_SN6IM2, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN6IM2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    // lv_obj_clear_flag(ui_SN6IM2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN6IM3 = lv_img_create(ui_SN6IM1);
    lv_img_set_src(ui_SN6IM3, &ui_img_1082659618);
    lv_obj_set_width(ui_SN6IM3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6IM3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6IM3, 140);
    lv_obj_set_y(ui_SN6IM3, 0);
    lv_obj_set_align(ui_SN6IM3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6IM3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN6IM3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN6BAR1 = lv_bar_create(ui_SN6IM1);
    lv_bar_set_value(ui_SN6BAR1, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SN6BAR1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SN6BAR1, 11);
    lv_obj_set_height(ui_SN6BAR1, 20);
    lv_obj_set_x(ui_SN6BAR1, 139);
    lv_obj_set_y(ui_SN6BAR1, 1);
    lv_obj_set_align(ui_SN6BAR1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SN6BAR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6BAR1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6BAR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SN6BAR1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6BAR1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6BAR1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SN6IM6 = lv_img_create(ui_SN6IM1);
    lv_img_set_src(ui_SN6IM6, &ui_img_1292609536);
    lv_obj_set_width(ui_SN6IM6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6IM6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6IM6, 139);
    lv_obj_set_y(ui_SN6IM6, 0);
    lv_obj_set_align(ui_SN6IM6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6IM6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_SN6IM6, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN6IM6, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN6LAB1 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB1, 170);
    lv_obj_set_y(ui_SN6LAB1, 0);
    lv_obj_set_align(ui_SN6LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB1, "100");
    lv_obj_set_style_text_color(ui_SN6LAB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6LAB2 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB2, 200);
    lv_obj_set_y(ui_SN6LAB2, 0);
    lv_obj_set_align(ui_SN6LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB2, "%");
    lv_obj_set_style_text_color(ui_SN6LAB2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6LAB3 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB3, -200);
    lv_obj_set_y(ui_SN6LAB3, 0);
    lv_obj_set_align(ui_SN6LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB3, "HH");
    lv_obj_set_style_text_color(ui_SN6LAB3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6LAB4 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB4, -160);
    lv_obj_set_y(ui_SN6LAB4, 0);
    lv_obj_set_align(ui_SN6LAB4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB4, "MM");
    lv_obj_set_style_text_color(ui_SN6LAB4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6LAB5 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB5, -181);
    lv_obj_set_y(ui_SN6LAB5, 0);
    lv_obj_set_align(ui_SN6LAB5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB5, ":");
    lv_obj_set_style_text_color(ui_SN6LAB5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6LAB6 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB6, -110);
    lv_obj_set_y(ui_SN6LAB6, 0);
    lv_obj_set_align(ui_SN6LAB6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB6, "DD");
    lv_obj_set_style_text_color(ui_SN6LAB6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6LAB7 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB7, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB7, -85);
    lv_obj_set_y(ui_SN6LAB7, 0);
    lv_obj_set_align(ui_SN6LAB7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB7, "-");
    lv_obj_set_style_text_color(ui_SN6LAB7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6LAB8 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB8, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB8, -60);
    lv_obj_set_y(ui_SN6LAB8, 0);
    lv_obj_set_align(ui_SN6LAB8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB8, "MM");
    lv_obj_set_style_text_color(ui_SN6LAB8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6LAB9 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB9, -35);
    lv_obj_set_y(ui_SN6LAB9, 0);
    lv_obj_set_align(ui_SN6LAB9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB9, "-");
    lv_obj_set_style_text_color(ui_SN6LAB9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6LAB10 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB10, 0);
    lv_obj_set_y(ui_SN6LAB10, 0);
    lv_obj_set_align(ui_SN6LAB10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB10, "YYYY");
    lv_obj_set_style_text_color(ui_SN6LAB10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6LAB11 = lv_label_create(ui_SN6IM1);
    lv_obj_set_width(ui_SN6LAB11, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6LAB11, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6LAB11, 70);
    lv_obj_set_y(ui_SN6LAB11, 0);
    lv_obj_set_align(ui_SN6LAB11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6LAB11, Version_String_Buff);
    lv_obj_set_style_text_color(ui_SN6LAB11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6LAB11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6LAB11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6IM4 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_SN6IM4, &ui_img_tg_logo_rgb_128_png);
    lv_obj_set_width(ui_SN6IM4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6IM4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6IM4, 141);
    lv_obj_set_y(ui_SN6IM4, 356);
    lv_obj_set_align(ui_SN6IM4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6IM4, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN6IM4, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // ui_SN6PNL1 = lv_obj_create(ui_Screen6);
    // lv_obj_set_width(ui_SN6PNL1, 60);
    // lv_obj_set_height(ui_SN6PNL1, 30);
    // lv_obj_set_x(ui_SN6PNL1, 0);
    // lv_obj_set_y(ui_SN6PNL1, -195);
    // lv_obj_set_align(ui_SN6PNL1, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN6PNL1, LV_OBJ_FLAG_HIDDEN); /// Flags
    // lv_obj_set_style_bg_color(ui_SN6PNL1, lv_color_hex(0x808991), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_SN6PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL1 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL1, 480);
    lv_obj_set_height(ui_SN6PNL1, 800);
    lv_obj_set_x(ui_SN6PNL1, 0);
    lv_obj_set_y(ui_SN6PNL1, 0);
    lv_obj_set_align(ui_SN6PNL1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SN6PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_border_color(ui_SN6PNL1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT); // 边框厚度设置为0
    lv_obj_set_style_bg_opa(ui_SN6PNL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL1IM1 = lv_img_create(ui_SN6PNL1);
    lv_img_set_src(ui_SN6PNL1IM1, &ui_img_682500442);
    lv_obj_set_width(ui_SN6PNL1IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL1IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL1IM1, -220);
    lv_obj_set_y(ui_SN6PNL1IM1, -290);
    lv_obj_set_align(ui_SN6PNL1IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL1IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN6PNL1IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN6PNL1BTN1 = lv_btn_create(ui_SN6PNL1);
    lv_obj_set_width(ui_SN6PNL1BTN1, 80);
    lv_obj_set_height(ui_SN6PNL1BTN1, 35);
    lv_obj_set_x(ui_SN6PNL1BTN1, -170);
    lv_obj_set_y(ui_SN6PNL1BTN1, -290);
    lv_obj_set_align(ui_SN6PNL1BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL1BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN6PNL1BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN6PNL1BTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6PNL1BTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN6PNL1BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN6PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL1BTN1LAB1 = lv_label_create(ui_SN6PNL1BTN1);
    lv_obj_set_width(ui_SN6PNL1BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL1BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL1BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL1BTN1LAB1, "返回");
    lv_obj_set_style_text_color(ui_SN6PNL1BTN1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL1BTN1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL1BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6BAR2 = lv_bar_create(ui_Screen6);
    lv_bar_set_value(ui_SN6BAR2, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SN6BAR2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SN6BAR2, 180);
    lv_obj_set_height(ui_SN6BAR2, 180);
    lv_obj_set_x(ui_SN6BAR2, -130);
    lv_obj_set_y(ui_SN6BAR2, -175);
    lv_obj_set_align(ui_SN6BAR2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SN6BAR2, lv_color_hex(0x808991), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6BAR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SN6BAR2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6BAR2, lv_color_hex(0xFCC917), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6BAR2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SN6BAR3 = lv_bar_create(ui_Screen6);
    lv_bar_set_value(ui_SN6BAR3, 0, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SN6BAR3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SN6BAR3, 180);
    lv_obj_set_height(ui_SN6BAR3, 180);
    lv_obj_set_x(ui_SN6BAR3, 130);
    lv_obj_set_y(ui_SN6BAR3, -175);
    lv_obj_set_align(ui_SN6BAR3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SN6BAR3, lv_color_hex(0x808991), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6BAR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SN6BAR3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6BAR3, lv_color_hex(0xFCC917), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6BAR3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SN6BAR4 = lv_bar_create(ui_Screen6);
    lv_obj_set_width(ui_SN6BAR4, 100);
    lv_obj_set_height(ui_SN6BAR4, 40);
    lv_obj_set_x(ui_SN6BAR4, 0);
    lv_obj_set_y(ui_SN6BAR4, -175);
    lv_obj_set_align(ui_SN6BAR4, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SN6BAR4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6BAR4, lv_color_hex(0x808991), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6BAR4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SN6BAR4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6BAR4, lv_color_hex(0x07FB6B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6BAR4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SN6BAR4LAB1 = lv_label_create(ui_SN6BAR4);
    lv_obj_set_width(ui_SN6BAR4LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6BAR4LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6BAR4LAB1, -23);
    lv_obj_set_y(ui_SN6BAR4LAB1, 0);
    lv_obj_set_align(ui_SN6BAR4LAB1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6BAR4LAB1, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_label_set_text(ui_SN6BAR4LAB1, "00");
    lv_obj_set_style_text_color(ui_SN6BAR4LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6BAR4LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6BAR4LAB1, &ui_font_HEI24x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6BAR4LAB2 = lv_label_create(ui_SN6BAR4);
    lv_obj_set_width(ui_SN6BAR4LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6BAR4LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6BAR4LAB2, 0);
    lv_obj_set_y(ui_SN6BAR4LAB2, -3);
    lv_obj_set_align(ui_SN6BAR4LAB2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6BAR4LAB2, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_label_set_text(ui_SN6BAR4LAB2, ":");
    lv_obj_set_style_text_color(ui_SN6BAR4LAB2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6BAR4LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6BAR4LAB2, &ui_font_HEI24x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6BAR4LAB3 = lv_label_create(ui_SN6BAR4);
    lv_obj_set_width(ui_SN6BAR4LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6BAR4LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6BAR4LAB3, 23);
    lv_obj_set_y(ui_SN6BAR4LAB3, 0);
    lv_obj_set_align(ui_SN6BAR4LAB3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6BAR4LAB3, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_label_set_text(ui_SN6BAR4LAB3, "50");
    lv_obj_set_style_text_color(ui_SN6BAR4LAB3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6BAR4LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6BAR4LAB3, &ui_font_HEI24x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL2 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL2, 288);
    lv_obj_set_height(ui_SN6PNL2, 60);
    lv_obj_set_x(ui_SN6PNL2, -81);
    lv_obj_set_y(ui_SN6PNL2, 359);
    lv_obj_set_align(ui_SN6PNL2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SN6PNL2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL2LAB1 = lv_label_create(ui_SN6PNL2);
    lv_obj_set_width(ui_SN6PNL2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL2LAB1, -80);
    lv_obj_set_y(ui_SN6PNL2LAB1, -15);
    lv_obj_set_align(ui_SN6PNL2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL2LAB1, "客戶資料: ");
    lv_obj_set_style_text_color(ui_SN6PNL2LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL2LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL2LAB1, &ui_font_HEI18X4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL2LAB2 = lv_label_create(ui_SN6PNL2);
    lv_obj_set_width(ui_SN6PNL2LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL2LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL2LAB2, -82);
    lv_obj_set_y(ui_SN6PNL2LAB2, 10);
    lv_obj_set_align(ui_SN6PNL2LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL2LAB2, "測試模式:");
    lv_obj_set_style_text_color(ui_SN6PNL2LAB2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL2LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL2LAB2, &ui_font_HEI18X4, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN6PNL2LAB3 = lv_label_create(ui_SN6PNL2);
    // lv_obj_set_width(ui_SN6PNL2LAB3, LV_SIZE_CONTENT);  /// 1
    // lv_obj_set_height(ui_SN6PNL2LAB3, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_SN6PNL2LAB3, 15);
    // lv_obj_set_y(ui_SN6PNL2LAB3, -15);
    // lv_obj_set_align(ui_SN6PNL2LAB3, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_SN6PNL2LAB3, "123456");
    // lv_obj_set_style_text_color(ui_SN6PNL2LAB3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_SN6PNL2LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_SN6PNL2LAB3, &ui_font_HEI18X4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL2LAB3 = lv_label_create(ui_SN6PNL2);
    lv_obj_set_width(ui_SN6PNL2LAB3, 100); // 1
    lv_obj_set_height(ui_SN6PNL2LAB3, 17); // 1
    lv_obj_set_x(ui_SN6PNL2LAB3, 25);
    lv_obj_set_y(ui_SN6PNL2LAB3, -15);
    lv_obj_set_align(ui_SN6PNL2LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL2LAB3, "123456");

    lv_label_set_long_mode(ui_SN6PNL2LAB3, LV_LABEL_LONG_DOT);                        // 使用LV_LABEL_LONG_SCROLL模式实现水平滚动
    lv_obj_set_style_anim_speed(ui_SN6PNL2LAB3, 50, LV_PART_MAIN | LV_STATE_DEFAULT); /* 设置滚动速度 */
    lv_obj_set_style_text_color(ui_SN6PNL2LAB3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL2LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL2LAB3, &ui_font_HEI18X4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL2LAB4 = lv_label_create(ui_SN6PNL2);
    lv_obj_set_width(ui_SN6PNL2LAB4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL2LAB4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL2LAB4, 0);
    lv_obj_set_y(ui_SN6PNL2LAB4, 10);
    lv_obj_set_align(ui_SN6PNL2LAB4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL2LAB4, "內喉");
    lv_obj_set_style_text_color(ui_SN6PNL2LAB4, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL2LAB4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL2LAB4, &ui_font_HEI18X4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL3 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL3, 480);
    lv_obj_set_height(ui_SN6PNL3, 110);
    lv_obj_set_x(ui_SN6PNL3, 0);
    lv_obj_set_y(ui_SN6PNL3, -25);
    lv_obj_set_align(ui_SN6PNL3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SN6PNL3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL3LAB1 = lv_label_create(ui_SN6PNL3);
    lv_obj_set_width(ui_SN6PNL3LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL3LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL3LAB1, -80);
    lv_obj_set_y(ui_SN6PNL3LAB1, 5);
    lv_obj_set_align(ui_SN6PNL3LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL3LAB1, "0.0");
    lv_obj_set_style_text_color(ui_SN6PNL3LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL3LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL3LAB1, &ui_font_HEI100x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL3PNL1 = lv_obj_create(ui_SN6PNL3);
    lv_obj_set_width(ui_SN6PNL3PNL1, 200);
    lv_obj_set_height(ui_SN6PNL3PNL1, 70);
    lv_obj_set_x(ui_SN6PNL3PNL1, 190);
    lv_obj_set_y(ui_SN6PNL3PNL1, 5);
    lv_obj_set_align(ui_SN6PNL3PNL1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SN6PNL3PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL3PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL3PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL3PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL3PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL3PNL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL3PNL1LAB1 = lv_label_create(ui_SN6PNL3PNL1);
    lv_obj_set_width(ui_SN6PNL3PNL1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL3PNL1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL3PNL1LAB1, -30);
    lv_obj_set_y(ui_SN6PNL3PNL1LAB1, 0);
    lv_obj_set_align(ui_SN6PNL3PNL1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL3PNL1LAB1, "inH 0");
    lv_obj_set_style_text_color(ui_SN6PNL3PNL1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL3PNL1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL3PNL1LAB1, &ui_font_HEI45x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL3PNL1LAB2 = lv_label_create(ui_SN6PNL3PNL1);
    lv_obj_set_width(ui_SN6PNL3PNL1LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL3PNL1LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL3PNL1LAB2, -11);
    lv_obj_set_y(ui_SN6PNL3PNL1LAB2, 12);
    lv_obj_set_align(ui_SN6PNL3PNL1LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL3PNL1LAB2, "2");
    lv_obj_add_flag(ui_SN6PNL3PNL1LAB2, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6PNL3PNL1LAB2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL3PNL1LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL3PNL1LAB2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL4 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL4, 480);
    lv_obj_set_height(ui_SN6PNL4, 50);
    lv_obj_set_x(ui_SN6PNL4, 0);
    lv_obj_set_y(ui_SN6PNL4, 45);
    lv_obj_set_align(ui_SN6PNL4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SN6PNL4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL4LAB1 = lv_label_create(ui_SN6PNL4);
    lv_obj_set_width(ui_SN6PNL4LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL4LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL4LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL4LAB1, "供氣閥測試中...");
    lv_obj_add_flag(ui_SN6PNL4LAB1, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6PNL4LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL4LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL4LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL4LAB2 = lv_label_create(ui_SN6PNL4);
    lv_obj_set_width(ui_SN6PNL4LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL4LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL4LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL4LAB2, "降壓中...");
    lv_obj_add_flag(ui_SN6PNL4LAB2, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6PNL4LAB2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL4LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL4LAB2, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL4LAB3 = lv_label_create(ui_SN6PNL4);
    lv_obj_set_width(ui_SN6PNL4LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL4LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL4LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL4LAB3, "測試合格");
    lv_obj_add_flag(ui_SN6PNL4LAB3, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6PNL4LAB3, lv_color_hex(0x17FC1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL4LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL4LAB3, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL4LAB4 = lv_label_create(ui_SN6PNL4);
    lv_obj_set_width(ui_SN6PNL4LAB4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL4LAB4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL4LAB4, 0);
    lv_obj_set_y(ui_SN6PNL4LAB4, 9);
    lv_obj_set_align(ui_SN6PNL4LAB4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL4LAB4, "壓力測試中...");
    lv_obj_add_flag(ui_SN6PNL4LAB4, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6PNL4LAB4, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL4LAB4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL4LAB4, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL4LAB5 = lv_label_create(ui_SN6PNL4);
    lv_obj_set_width(ui_SN6PNL4LAB5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL4LAB5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL4LAB5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL4LAB5, "試漏失敗");
    lv_obj_add_flag(ui_SN6PNL4LAB5, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6PNL4LAB5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL4LAB5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL4LAB5, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL5 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL5, 420);
    lv_obj_set_height(ui_SN6PNL5, 154);
    lv_obj_set_x(ui_SN6PNL5, 0);
    lv_obj_set_y(ui_SN6PNL5, 250);
    lv_obj_set_align(ui_SN6PNL5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL5, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN6PNL5, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL5, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL5LAB1 = lv_label_create(ui_SN6PNL5);
    lv_obj_set_width(ui_SN6PNL5LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL5LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL5LAB1, -115);
    lv_obj_set_y(ui_SN6PNL5LAB1, -30);
    lv_obj_set_align(ui_SN6PNL5LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL5LAB1, "客戶資料: ");
    lv_obj_set_style_text_color(ui_SN6PNL5LAB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL5LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL5LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL5LAB2 = lv_label_create(ui_SN6PNL5);
    lv_obj_set_width(ui_SN6PNL5LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL5LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL5LAB2, -115);
    lv_obj_set_y(ui_SN6PNL5LAB2, 30);
    lv_obj_set_align(ui_SN6PNL5LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL5LAB2, "測試模式:");
    lv_obj_set_style_text_color(ui_SN6PNL5LAB2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL5LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL5LAB2, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_SN6PNL5LAB3 = lv_label_create(ui_SN6PNL5);
    // lv_obj_set_width(ui_SN6PNL5LAB3, LV_SIZE_CONTENT);  /// 1
    // lv_obj_set_height(ui_SN6PNL5LAB3, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_SN6PNL5LAB3, 75);
    // lv_obj_set_y(ui_SN6PNL5LAB3, -30);
    // lv_obj_set_align(ui_SN6PNL5LAB3, LV_ALIGN_CENTER);
    // lv_label_set_text(ui_SN6PNL5LAB3, "1234567890");
    // lv_obj_set_style_text_color(ui_SN6PNL5LAB3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_opa(ui_SN6PNL5LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_text_font(ui_SN6PNL5LAB3, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL5LAB3 = lv_label_create(ui_SN6PNL5);
    lv_obj_set_width(ui_SN6PNL5LAB3, 180); // 1
    lv_obj_set_height(ui_SN6PNL5LAB3, 30); // 1
    lv_obj_set_x(ui_SN6PNL5LAB3, 75);
    lv_obj_set_y(ui_SN6PNL5LAB3, -30);
    lv_obj_set_align(ui_SN6PNL5LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL5LAB3, "1234567890");
    lv_label_set_long_mode(ui_SN6PNL5LAB3, LV_LABEL_LONG_DOT);                        // 使用LV_LABEL_LONG_SCROLL模式实现水平滚动
    lv_obj_set_style_anim_speed(ui_SN6PNL5LAB3, 50, LV_PART_MAIN | LV_STATE_DEFAULT); /* 设置滚动速度 */
    lv_obj_set_style_text_color(ui_SN6PNL5LAB3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL5LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL5LAB3, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL5LAB4 = lv_label_create(ui_SN6PNL5);
    lv_obj_set_width(ui_SN6PNL5LAB4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL5LAB4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL5LAB4, 50);
    lv_obj_set_y(ui_SN6PNL5LAB4, 30);
    lv_obj_set_align(ui_SN6PNL5LAB4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL5LAB4, "內喉");
    lv_obj_set_style_text_color(ui_SN6PNL5LAB4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL5LAB4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL5LAB4, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL6 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL6, 480);
    lv_obj_set_height(ui_SN6PNL6, 30);
    lv_obj_set_x(ui_SN6PNL6, 0);
    lv_obj_set_y(ui_SN6PNL6, 90);
    lv_obj_set_align(ui_SN6PNL6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL6, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN6PNL6, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL6IM1 = lv_img_create(ui_SN6PNL6);
    lv_img_set_src(ui_SN6PNL6IM1, &ui_img_2019467334);
    lv_obj_set_width(ui_SN6PNL6IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL6IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL6IM1, -60);
    lv_obj_set_y(ui_SN6PNL6IM1, 0);
    lv_obj_set_align(ui_SN6PNL6IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL6IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN6PNL6IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN6PNL6LAB1 = lv_label_create(ui_SN6PNL6);
    lv_obj_set_width(ui_SN6PNL6LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL6LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL6LAB1, 30);
    lv_obj_set_y(ui_SN6PNL6LAB1, 0);
    lv_obj_set_align(ui_SN6PNL6LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL6LAB1, "(請拍照紀錄)");
    lv_obj_set_style_text_color(ui_SN6PNL6LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL6LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL6LAB1, &ui_font_HEI22x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL7 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL7, 480);
    lv_obj_set_height(ui_SN6PNL7, 40);
    lv_obj_set_x(ui_SN6PNL7, 0);
    lv_obj_set_y(ui_SN6PNL7, 140);
    lv_obj_set_align(ui_SN6PNL7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL7, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN6PNL7, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL7PNL1 = lv_obj_create(ui_SN6PNL7);
    lv_obj_set_width(ui_SN6PNL7PNL1, 120);
    lv_obj_set_height(ui_SN6PNL7PNL1, 40);
    lv_obj_set_x(ui_SN6PNL7PNL1, 140);
    lv_obj_set_y(ui_SN6PNL7PNL1, 0);
    lv_obj_set_align(ui_SN6PNL7PNL1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SN6PNL7PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL7PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL7PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL7PNL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL7PNL1LAB1 = lv_label_create(ui_SN6PNL7PNL1);
    lv_obj_set_width(ui_SN6PNL7PNL1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL7PNL1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL7PNL1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL7PNL1LAB1, "inH 0");
    lv_obj_set_style_text_color(ui_SN6PNL7PNL1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL7PNL1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL7PNL1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL7PNL1LAB2 = lv_label_create(ui_SN6PNL7PNL1);
    lv_obj_set_width(ui_SN6PNL7PNL1LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL7PNL1LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL7PNL1LAB2, 14);
    lv_obj_set_y(ui_SN6PNL7PNL1LAB2, 8);
    lv_obj_set_align(ui_SN6PNL7PNL1LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL7PNL1LAB2, "2");
    // lv_obj_add_flag(ui_SN6PNL7PNL1LAB2, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6PNL7PNL1LAB2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL7PNL1LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL7PNL1LAB2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL7PNL1LAB3 = lv_label_create(ui_SN6PNL7PNL1);
    lv_obj_set_width(ui_SN6PNL7PNL1LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL7PNL1LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL7PNL1LAB3, 30);
    lv_obj_set_y(ui_SN6PNL7PNL1LAB3, 0);
    lv_obj_set_align(ui_SN6PNL7PNL1LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL7PNL1LAB3, "O");
    lv_obj_add_flag(ui_SN6PNL7PNL1LAB3, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6PNL7PNL1LAB3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL7PNL1LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL7PNL1LAB3, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL7LAB1 = lv_label_create(ui_SN6PNL7);
    lv_obj_set_width(ui_SN6PNL7LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL7LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL7LAB1, 35);
    lv_obj_set_y(ui_SN6PNL7LAB1, 0);
    lv_obj_set_align(ui_SN6PNL7LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL7LAB1, "0.2");
    lv_obj_set_style_text_color(ui_SN6PNL7LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL7LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL7LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL7LAB2 = lv_label_create(ui_SN6PNL7);
    lv_obj_set_width(ui_SN6PNL7LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL7LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL7LAB2, -80);
    lv_obj_set_y(ui_SN6PNL7LAB2, 0);
    lv_obj_set_align(ui_SN6PNL7LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL7LAB2, "氣壓下降:");
    lv_obj_set_style_text_color(ui_SN6PNL7LAB2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL7LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL7LAB2, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL8 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL8, 200);
    lv_obj_set_height(ui_SN6PNL8, 50);
    lv_obj_set_x(ui_SN6PNL8, -104);
    lv_obj_set_y(ui_SN6PNL8, 359);
    lv_obj_set_align(ui_SN6PNL8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL8, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN6PNL8, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL8IM1 = lv_img_create(ui_SN6PNL8);
    lv_img_set_src(ui_SN6PNL8IM1, &ui_img_682500442);
    lv_obj_set_width(ui_SN6PNL8IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL8IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL8IM1, -89);
    lv_obj_set_y(ui_SN6PNL8IM1, 0);
    lv_obj_set_align(ui_SN6PNL8IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL8IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN6PNL8IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN6PNL8BTN1 = lv_btn_create(ui_SN6PNL8);
    lv_obj_set_width(ui_SN6PNL8BTN1, 160);
    lv_obj_set_height(ui_SN6PNL8BTN1, 40);
    lv_obj_set_x(ui_SN6PNL8BTN1, 4);
    lv_obj_set_y(ui_SN6PNL8BTN1, -5);
    lv_obj_set_align(ui_SN6PNL8BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL8BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN6PNL8BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN6PNL8BTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6PNL8BTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL8BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN6PNL8BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN6PNL8BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL8BTN1LAB1 = lv_label_create(ui_SN6PNL8BTN1);
    lv_obj_set_width(ui_SN6PNL8BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL8BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL8BTN1LAB1, 0);
    lv_obj_set_y(ui_SN6PNL8BTN1LAB1, 4);
    lv_obj_set_align(ui_SN6PNL8BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL8BTN1LAB1, "返回主目錄");
    lv_obj_set_style_text_color(ui_SN6PNL8BTN1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL8BTN1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL8BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL9 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL9, 480);
    lv_obj_set_height(ui_SN6PNL9, 200);
    lv_obj_set_x(ui_SN6PNL9, 0);
    lv_obj_set_y(ui_SN6PNL9, 190);
    lv_obj_set_align(ui_SN6PNL9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SN6PNL9, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL9BTN1 = lv_btn_create(ui_SN6PNL9);
    lv_obj_set_width(ui_SN6PNL9BTN1, 220);
    lv_obj_set_height(ui_SN6PNL9BTN1, 76);
    lv_obj_set_x(ui_SN6PNL9BTN1, -100);
    lv_obj_set_y(ui_SN6PNL9BTN1, 50);
    lv_obj_set_align(ui_SN6PNL9BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL9BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN6PNL9BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN6PNL9BTN1, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6PNL9BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL9BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL9BTN1LAB1 = lv_label_create(ui_SN6PNL9BTN1);
    lv_obj_set_width(ui_SN6PNL9BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL9BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL9BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL9BTN1LAB1, "開始");
    lv_obj_set_style_text_font(ui_SN6PNL9BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL9BTN2 = lv_btn_create(ui_SN6PNL9);
    lv_obj_set_width(ui_SN6PNL9BTN2, 153);
    lv_obj_set_height(ui_SN6PNL9BTN2, 76);
    lv_obj_set_x(ui_SN6PNL9BTN2, 130);
    lv_obj_set_y(ui_SN6PNL9BTN2, 50);
    lv_obj_set_align(ui_SN6PNL9BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL9BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN6PNL9BTN2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN6PNL9BTN2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6PNL9BTN2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL9BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL9BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL9BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL9BTN2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SN6PNL9BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL9BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL9BTN2LAB1 = lv_label_create(ui_SN6PNL9BTN2);
    lv_obj_set_width(ui_SN6PNL9BTN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL9BTN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL9BTN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL9BTN2LAB1, "歸零");
    lv_obj_set_style_text_font(ui_SN6PNL9BTN2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL9LAB1 = lv_label_create(ui_SN6PNL9);
    lv_obj_set_width(ui_SN6PNL9LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL9LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL9LAB1, 0);
    lv_obj_set_y(ui_SN6PNL9LAB1, -60);
    lv_obj_set_align(ui_SN6PNL9LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL9LAB1, "請接駁喉管及關掣");
    lv_obj_set_style_text_color(ui_SN6PNL9LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL9LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL9LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL10 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL10, 480);
    lv_obj_set_height(ui_SN6PNL10, 130);
    lv_obj_set_x(ui_SN6PNL10, 0);
    lv_obj_set_y(ui_SN6PNL10, 240);
    lv_obj_set_align(ui_SN6PNL10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SN6PNL10, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_add_flag(ui_SN6PNL10, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL10BTN1 = lv_btn_create(ui_SN6PNL10);
    lv_obj_set_width(ui_SN6PNL10BTN1, 220);
    lv_obj_set_height(ui_SN6PNL10BTN1, 75);
    lv_obj_set_x(ui_SN6PNL10BTN1, -100);
    lv_obj_set_y(ui_SN6PNL10BTN1, 25);
    lv_obj_set_align(ui_SN6PNL10BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL10BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN6PNL10BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN6PNL10BTN1, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6PNL10BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL10BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL10BTN1LAB1 = lv_label_create(ui_SN6PNL10BTN1);
    lv_obj_set_width(ui_SN6PNL10BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL10BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL10BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL10BTN1LAB1, "重新測試");
    lv_obj_set_style_text_font(ui_SN6PNL10BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL10BTN2 = lv_btn_create(ui_SN6PNL10);
    lv_obj_set_width(ui_SN6PNL10BTN2, 153);
    lv_obj_set_height(ui_SN6PNL10BTN2, 75);
    lv_obj_set_x(ui_SN6PNL10BTN2, 125);
    lv_obj_set_y(ui_SN6PNL10BTN2, 25);
    lv_obj_set_align(ui_SN6PNL10BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL10BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN6PNL10BTN2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN6PNL10BTN2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6PNL10BTN2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL10BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL10BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL10BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL10BTN2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SN6PNL10BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL10BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL10BTN2LAB1 = lv_label_create(ui_SN6PNL10BTN2);
    lv_obj_set_width(ui_SN6PNL10BTN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL10BTN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL10BTN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL10BTN2LAB1, "完成");
    lv_obj_set_style_text_font(ui_SN6PNL10BTN2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    green_meter = lv_meter_create(ui_Screen6);
    /*Remove the background and the circle from the middle*/
    lv_obj_remove_style(green_meter, NULL, LV_PART_MAIN);
    lv_obj_remove_style(green_meter, NULL, LV_PART_INDICATOR);
    lv_obj_set_size(green_meter, 180, 180);
    lv_obj_align(green_meter, LV_ALIGN_LEFT_MID, 20, -175);

    /*Add a scale first with no ticks.*/
    green_scale = lv_meter_add_scale(green_meter);
    lv_meter_set_scale_ticks(green_meter, green_scale, 12, 0, 4, lv_color_black());
    // lv_meter_set_scale_major_ticks(green_meter, green_scale, 3, 2, 4, lv_color_hex3(0xeee), 0);
    lv_meter_set_scale_range(green_meter, green_scale, 0, 360, 360, 270);
    /*Add a three arc indicator*/
    lv_coord_t indic_g = 100;
    indic1 = lv_meter_add_arc(green_meter, green_scale, indic_g, lv_color_hex(0xFCC917), 0);
    lv_meter_set_indicator_start_value(green_meter, indic1, 0);
    lv_meter_set_indicator_end_value(green_meter, indic1, 0);

    red_meter = lv_meter_create(ui_Screen6);
    lv_obj_remove_style(red_meter, NULL, LV_PART_MAIN);
    lv_obj_remove_style(red_meter, NULL, LV_PART_INDICATOR);
    lv_obj_set_size(red_meter, 180, 180);
    lv_obj_align(red_meter, LV_ALIGN_RIGHT_MID, -20, -175);

    red_scale = lv_meter_add_scale(red_meter);
    lv_meter_set_scale_ticks(red_meter, red_scale, 0, 0, 0, lv_color_black());
    lv_meter_set_scale_range(red_meter, red_scale, 0, 360, 360, 270);
    lv_coord_t indic_r = 100;
    indic2 = lv_meter_add_arc(red_meter, red_scale, indic_r, lv_color_hex(0xFCC917), 0);
    lv_meter_set_indicator_start_value(red_meter, indic2, 0);
    lv_meter_set_indicator_end_value(red_meter, indic2, 0);

    ui_SN6BAR2LAB1 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_SN6BAR2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6BAR2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6BAR2LAB1, -170);
    lv_obj_set_y(ui_SN6BAR2LAB1, -175);
    lv_obj_set_align(ui_SN6BAR2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6BAR2LAB1, "01");
    lv_obj_add_flag(ui_SN6BAR2LAB1, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6BAR2LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6BAR2LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6BAR2LAB1, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6BAR2LAB2 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_SN6BAR2LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6BAR2LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6BAR2LAB2, -130);
    lv_obj_set_y(ui_SN6BAR2LAB2, -175);
    lv_obj_set_align(ui_SN6BAR2LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6BAR2LAB2, ":");
    lv_obj_add_flag(ui_SN6BAR2LAB2, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6BAR2LAB2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6BAR2LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6BAR2LAB2, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6BAR2LAB3 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_SN6BAR2LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6BAR2LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6BAR2LAB3, -90);
    lv_obj_set_y(ui_SN6BAR2LAB3, -175);
    lv_obj_set_align(ui_SN6BAR2LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6BAR2LAB3, "30");
    lv_obj_add_flag(ui_SN6BAR2LAB3, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6BAR2LAB3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6BAR2LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6BAR2LAB3, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6BAR3LAB1 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_SN6BAR3LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6BAR3LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6BAR3LAB1, 90);
    lv_obj_set_y(ui_SN6BAR3LAB1, -175);
    lv_obj_set_align(ui_SN6BAR3LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6BAR3LAB1, "00");
    lv_obj_add_flag(ui_SN6BAR3LAB1, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6BAR3LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6BAR3LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6BAR3LAB1, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6BAR3LAB2 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_SN6BAR3LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6BAR3LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6BAR3LAB2, 130);
    lv_obj_set_y(ui_SN6BAR3LAB2, -175);
    lv_obj_set_align(ui_SN6BAR3LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6BAR3LAB2, ":");
    lv_obj_add_flag(ui_SN6BAR3LAB2, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6BAR3LAB2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6BAR3LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6BAR3LAB2, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6BAR3LAB3 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_SN6BAR3LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6BAR3LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6BAR3LAB3, 170);
    lv_obj_set_y(ui_SN6BAR3LAB3, -175);
    lv_obj_set_align(ui_SN6BAR3LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6BAR3LAB3, "30");
    lv_obj_add_flag(ui_SN6BAR3LAB3, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_text_color(ui_SN6BAR3LAB3, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6BAR3LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6BAR3LAB3, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL11 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_SN6PNL11, 486);
    lv_obj_set_height(ui_SN6PNL11, 806);
    lv_obj_set_align(ui_SN6PNL11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL11, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN6PNL11, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_SN6PNL11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6PNL11, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL11PNL1 = lv_obj_create(ui_SN6PNL11);
    lv_obj_set_width(ui_SN6PNL11PNL1, 420);
    lv_obj_set_height(ui_SN6PNL11PNL1, 260);
    lv_obj_set_x(ui_SN6PNL11PNL1, 0);
    lv_obj_set_y(ui_SN6PNL11PNL1, -30);
    lv_obj_set_align(ui_SN6PNL11PNL1, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN6PNL11PNL1, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN6PNL11PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN6PNL11PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL11PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN6PNL11PNL1, lv_color_hex(0x06FC41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN6PNL11PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN6PNL11PNL1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL11PNL1BTN51 = lv_btn_create(ui_SN6PNL11PNL1);
    lv_obj_set_width(ui_SN6PNL11PNL1BTN51, 120);
    lv_obj_set_height(ui_SN6PNL11PNL1BTN51, 70);
    lv_obj_set_x(ui_SN6PNL11PNL1BTN51, -85);
    lv_obj_set_y(ui_SN6PNL11PNL1BTN51, 60);
    lv_obj_set_align(ui_SN6PNL11PNL1BTN51, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL11PNL1BTN51, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN6PNL11PNL1BTN51, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN6PNL11PNL1BTN51, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6PNL11PNL1BTN51, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL11PNL1BTN51, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL11PNL1BTN1LAB1 = lv_label_create(ui_SN6PNL11PNL1BTN51);
    lv_obj_set_width(ui_SN6PNL11PNL1BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL11PNL1BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL11PNL1BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL11PNL1BTN1LAB1, "確認");
    lv_obj_set_style_text_font(ui_SN6PNL11PNL1BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL11PNL1LAB1 = lv_label_create(ui_SN6PNL11PNL1);
    lv_obj_set_width(ui_SN6PNL11PNL1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL11PNL1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN6PNL11PNL1LAB1, 0);
    lv_obj_set_y(ui_SN6PNL11PNL1LAB1, -50);
    lv_obj_set_align(ui_SN6PNL11PNL1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL11PNL1LAB1, "是否確認關機");
    lv_obj_set_style_text_color(ui_SN6PNL11PNL1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN6PNL11PNL1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN6PNL11PNL1LAB1, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL11PNL1BTN2 = lv_btn_create(ui_SN6PNL11PNL1);
    lv_obj_set_width(ui_SN6PNL11PNL1BTN2, 120);
    lv_obj_set_height(ui_SN6PNL11PNL1BTN2, 70);
    lv_obj_set_x(ui_SN6PNL11PNL1BTN2, 85);
    lv_obj_set_y(ui_SN6PNL11PNL1BTN2, 60);
    lv_obj_set_align(ui_SN6PNL11PNL1BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN6PNL11PNL1BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN6PNL11PNL1BTN2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN6PNL11PNL1BTN2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN6PNL11PNL1BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN6PNL11PNL1BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN6PNL11PNL1BTN2LAB1 = lv_label_create(ui_SN6PNL11PNL1BTN2);
    lv_obj_set_width(ui_SN6PNL11PNL1BTN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN6PNL11PNL1BTN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN6PNL11PNL1BTN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN6PNL11PNL1BTN2LAB1, "取消");
    lv_obj_set_style_text_font(ui_SN6PNL11PNL1BTN2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SN6PNL1BTN1, ui_event_SN6PNL1BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN6PNL8BTN1, ui_event_SN6PNL8BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN6PNL9BTN1, ui_event_SN6PNL9BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN6PNL9BTN2, ui_event_SN6PNL9BTN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN6PNL10BTN1, ui_event_SN6PNL10BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN6PNL10BTN2, ui_event_SN6PNL10BTN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN6PNL11PNL1BTN51, ui_event_Shutdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN6PNL11PNL1BTN2, ui_event_Cancel, LV_EVENT_ALL, NULL);
}
