// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: DZSJN

#include "../ui.h"
#include "device_nvs.h"
void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2IM1 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_SN2IM1, &ui_img_rectangle_1_png);
    lv_obj_set_width(ui_SN2IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2IM1, 0);
    lv_obj_set_y(ui_SN2IM1, -365);
    lv_obj_set_align(ui_SN2IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN2IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // ui_SN2IM2 = lv_img_create(ui_SN2IM1);
    // lv_img_set_src(ui_SN2IM2, &ui_img_1551342831);
    // lv_obj_set_width(ui_SN2IM2, LV_SIZE_CONTENT);  /// 1
    // lv_obj_set_height(ui_SN2IM2, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_SN2IM2, 110);
    // lv_obj_set_y(ui_SN2IM2, 0);
    // lv_obj_set_align(ui_SN2IM2, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN2IM2, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    // lv_obj_clear_flag(ui_SN2IM2, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN2IM3 = lv_img_create(ui_SN2IM1);
    lv_img_set_src(ui_SN2IM3, &ui_img_1082659618);
    lv_obj_set_width(ui_SN2IM3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2IM3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2IM3, 140);
    lv_obj_set_y(ui_SN2IM3, 0);
    lv_obj_set_align(ui_SN2IM3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2IM3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN2IM3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN2Bar1 = lv_bar_create(ui_SN2IM1);
    lv_bar_set_value(ui_SN2Bar1, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SN2Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SN2Bar1, 11);
    lv_obj_set_height(ui_SN2Bar1, 20);
    lv_obj_set_x(ui_SN2Bar1, 139);
    lv_obj_set_y(ui_SN2Bar1, 1);
    lv_obj_set_align(ui_SN2Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SN2Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN2Bar1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2Bar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SN2Bar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN2Bar1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SN2IM6 = lv_img_create(ui_SN2IM1);
    lv_img_set_src(ui_SN2IM6, &ui_img_1292609536);
    lv_obj_set_width(ui_SN2IM6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2IM6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2IM6, 139);
    lv_obj_set_y(ui_SN2IM6, 0);
    lv_obj_set_align(ui_SN2IM6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2IM6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_SN2IM6, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN2IM6, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN2LAB1 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB1, 170);
    lv_obj_set_y(ui_SN2LAB1, 0);
    lv_obj_set_align(ui_SN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB1, "100");
    lv_obj_set_style_text_color(ui_SN2LAB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2LAB2 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB2, 200);
    lv_obj_set_y(ui_SN2LAB2, 0);
    lv_obj_set_align(ui_SN2LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB2, "%");
    lv_obj_set_style_text_color(ui_SN2LAB2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2LAB3 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB3, -200);
    lv_obj_set_y(ui_SN2LAB3, 0);
    lv_obj_set_align(ui_SN2LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB3, "HH");
    lv_obj_set_style_text_color(ui_SN2LAB3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2LAB4 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB4, -160);
    lv_obj_set_y(ui_SN2LAB4, 0);
    lv_obj_set_align(ui_SN2LAB4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB4, "MM");
    lv_obj_set_style_text_color(ui_SN2LAB4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2LAB5 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB5, -181);
    lv_obj_set_y(ui_SN2LAB5, 0);
    lv_obj_set_align(ui_SN2LAB5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB5, ":");
    lv_obj_set_style_text_color(ui_SN2LAB5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2LAB6 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB6, -110);
    lv_obj_set_y(ui_SN2LAB6, 0);
    lv_obj_set_align(ui_SN2LAB6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB6, "DD");
    lv_obj_set_style_text_color(ui_SN2LAB6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2LAB7 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB7, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB7, -85);
    lv_obj_set_y(ui_SN2LAB7, 0);
    lv_obj_set_align(ui_SN2LAB7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB7, "-");
    lv_obj_set_style_text_color(ui_SN2LAB7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2LAB8 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB8, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB8, -60);
    lv_obj_set_y(ui_SN2LAB8, 0);
    lv_obj_set_align(ui_SN2LAB8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB8, "MM");
    lv_obj_set_style_text_color(ui_SN2LAB8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2LAB9 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB9, -35);
    lv_obj_set_y(ui_SN2LAB9, 0);
    lv_obj_set_align(ui_SN2LAB9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB9, "-");
    lv_obj_set_style_text_color(ui_SN2LAB9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2LAB10 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB10, 0);
    lv_obj_set_y(ui_SN2LAB10, 0);
    lv_obj_set_align(ui_SN2LAB10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB10, "YYYY");
    lv_obj_set_style_text_color(ui_SN2LAB10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2LAB11 = lv_label_create(ui_SN2IM1);
    lv_obj_set_width(ui_SN2LAB11, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2LAB11, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2LAB11, 70);
    lv_obj_set_y(ui_SN2LAB11, 0);
    lv_obj_set_align(ui_SN2LAB11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2LAB11, Version_String_Buff);
    lv_obj_set_style_text_color(ui_SN2LAB11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2LAB11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2LAB11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2IM4 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_SN2IM4, &ui_img_1472549690);
    lv_obj_set_width(ui_SN2IM4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2IM4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2IM4, 0);
    lv_obj_set_y(ui_SN2IM4, 0);
    lv_obj_set_align(ui_SN2IM4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2IM4, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN2IM4, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    // ui_SN2IM5 = lv_img_create(ui_Screen2);
    // lv_img_set_src(ui_SN2IM5, &ui_img_1794843070);
    // lv_obj_set_width(ui_SN2IM5, LV_SIZE_CONTENT);  /// 1
    // lv_obj_set_height(ui_SN2IM5, LV_SIZE_CONTENT); /// 1
    // lv_obj_set_x(ui_SN2IM5, -6);
    // lv_obj_set_y(ui_SN2IM5, -244);
    // lv_obj_set_align(ui_SN2IM5, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN2IM5, LV_OBJ_FLAG_HIDDEN);       /// Flags
    // lv_obj_add_flag(ui_SN2IM5, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    // lv_obj_clear_flag(ui_SN2IM5, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN2PNL1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_SN2PNL1, 490);
    lv_obj_set_height(ui_SN2PNL1, 590);
    lv_obj_set_x(ui_SN2PNL1, 0);
    lv_obj_set_y(ui_SN2PNL1, 120);
    lv_obj_set_align(ui_SN2PNL1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL1, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN2PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_border_color(ui_SN2PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN2PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN2PNL1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL1IM1 = lv_img_create(ui_SN2PNL1);
    lv_img_set_src(ui_SN2PNL1IM1, &ui_img_path_3_png);
    lv_obj_set_width(ui_SN2PNL1IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL1IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL1IM1, 0);
    lv_obj_set_y(ui_SN2PNL1IM1, 0);
    lv_obj_set_align(ui_SN2PNL1IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL1IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN2PNL1IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN2PNL1LAB1 = lv_label_create(ui_SN2PNL1);
    lv_obj_set_width(ui_SN2PNL1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL1LAB1, -135);
    lv_obj_set_y(ui_SN2PNL1LAB1, -135);
    lv_obj_set_align(ui_SN2PNL1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL1LAB1, "員工編號:");
    lv_obj_set_style_text_color(ui_SN2PNL1LAB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL1LAB2 = lv_label_create(ui_SN2PNL1);
    lv_obj_set_width(ui_SN2PNL1LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL1LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL1LAB2, 30);
    lv_obj_set_y(ui_SN2PNL1LAB2, -135);
    lv_obj_set_align(ui_SN2PNL1LAB2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL1LAB2, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_label_set_text(ui_SN2PNL1LAB2, "123456");
    lv_obj_set_style_text_color(ui_SN2PNL1LAB2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL1LAB2, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL1LAB3 = lv_label_create(ui_SN2PNL1);
    lv_obj_set_width(ui_SN2PNL1LAB3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL1LAB3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL1LAB3, -135);
    lv_obj_set_y(ui_SN2PNL1LAB3, -50);
    lv_obj_set_align(ui_SN2PNL1LAB3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL1LAB3, "客戶資料:");
    lv_obj_set_style_text_color(ui_SN2PNL1LAB3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1LAB3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL1LAB3, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL1LAB4 = lv_label_create(ui_SN2PNL1);
    lv_obj_set_width(ui_SN2PNL1LAB4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL1LAB4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL1LAB4, -135);
    lv_obj_set_y(ui_SN2PNL1LAB4, 35);
    lv_obj_set_align(ui_SN2PNL1LAB4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL1LAB4, "測試模式: ");
    lv_obj_set_style_text_color(ui_SN2PNL1LAB4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1LAB4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL1LAB4, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL1LAB5 = lv_label_create(ui_SN2PNL1);
    lv_obj_set_width(ui_SN2PNL1LAB5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL1LAB5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL1LAB5, 147);
    lv_obj_set_y(ui_SN2PNL1LAB5, 261);
    lv_obj_set_align(ui_SN2PNL1LAB5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL1LAB5, my_nvs_Get_Device_ID());
    lv_obj_set_style_text_color(ui_SN2PNL1LAB5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1LAB5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL1LAB5, &ui_font_HEI18X4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL1TXT1 = lv_textarea_create(ui_SN2PNL1);
    lv_obj_set_width(ui_SN2PNL1TXT1, 270);
    lv_obj_set_height(ui_SN2PNL1TXT1, LV_SIZE_CONTENT); /// 50
    lv_obj_set_x(ui_SN2PNL1TXT1, 80);
    lv_obj_set_y(ui_SN2PNL1TXT1, -50);
    lv_obj_set_align(ui_SN2PNL1TXT1, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_SN2PNL1TXT1, "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_");
    lv_textarea_set_max_length(ui_SN2PNL1TXT1, 30);
    lv_textarea_set_placeholder_text(ui_SN2PNL1TXT1, "請輸入客戶資料....");
    lv_textarea_set_one_line(ui_SN2PNL1TXT1, true);
    lv_obj_set_style_text_color(ui_SN2PNL1TXT1, lv_color_hex(0x808991), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1TXT1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL1TXT1, &ui_font_HEI22x4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SN2PNL1TXT1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SN2PNL1TXT1, lv_color_hex(0x808991), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1TXT1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SN2PNL1TXT1, lv_color_hex(0x808991), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1TXT1, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SN2PNL1TXT1, lv_color_hex(0x808991), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1TXT1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_SN2PNL1TXT2 = lv_textarea_create(ui_SN2PNL1);
    lv_obj_set_width(ui_SN2PNL1TXT2, 270);
    lv_obj_set_height(ui_SN2PNL1TXT2, LV_SIZE_CONTENT); /// 50
    lv_obj_set_x(ui_SN2PNL1TXT2, 80);
    lv_obj_set_y(ui_SN2PNL1TXT2, -135);
    lv_obj_set_align(ui_SN2PNL1TXT2, LV_ALIGN_CENTER);
    // lv_textarea_set_accepted_chars(ui_SN2PNL1TXT2, "0123456789");
    lv_textarea_set_accepted_chars(ui_SN2PNL1TXT2, "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_");
    lv_textarea_set_max_length(ui_SN2PNL1TXT2, 6);
    lv_textarea_set_text(ui_SN2PNL1TXT2, "123456");
    lv_textarea_set_placeholder_text(ui_SN2PNL1TXT2, "請輸入員工號碼....");
    lv_textarea_set_one_line(ui_SN2PNL1TXT2, true);
    lv_obj_set_style_text_color(ui_SN2PNL1TXT2, lv_color_hex(0x808991), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1TXT2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL1TXT2, &ui_font_HEI22x4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SN2PNL1TXT2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SN2PNL1TXT2, lv_color_hex(0x808991), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1TXT2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SN2PNL1TXT2, lv_color_hex(0x808991), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1TXT2, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_SN2PNL1TXT2, lv_color_hex(0x808991), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1TXT2, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_SN2PNL1DPDN1 = lv_dropdown_create(ui_SN2PNL1);
    lv_dropdown_set_options(ui_SN2PNL1DPDN1, "內喉\n街喉\n自訂");
    lv_obj_set_width(ui_SN2PNL1DPDN1, 270);
    lv_obj_set_height(ui_SN2PNL1DPDN1, 50);
    lv_obj_set_x(ui_SN2PNL1DPDN1, 80);
    lv_obj_set_y(ui_SN2PNL1DPDN1, 35);
    lv_obj_set_align(ui_SN2PNL1DPDN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL1DPDN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_set_style_text_color(ui_SN2PNL1DPDN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1DPDN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL1DPDN1, &ui_font_HEI22x4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_SN2PNL1DPDN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_SN2PNL1DPDN1), lv_color_hex(0x002855),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_SN2PNL1DPDN1), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_SN2PNL1DPDN1), &ui_font_HEI22x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_SN2PNL1DPDN1), lv_color_hex(0x002855),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_SN2PNL1DPDN1), 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_SN2PNL1DPDN1), &ui_font_HEI22x4,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_dropdown_set_symbol(ui_SN2PNL1DPDN1, &ui_img_polygon_1_png); // arrow_image 是一个包含下拉箭头图片的lv_img_dsc_t变量

    ui_SN2PNL1BTN1 = lv_btn_create(ui_SN2PNL1);
    lv_obj_set_width(ui_SN2PNL1BTN1, 220);
    lv_obj_set_height(ui_SN2PNL1BTN1, 76);
    lv_obj_set_x(ui_SN2PNL1BTN1, 0);
    lv_obj_set_y(ui_SN2PNL1BTN1, 150);
    lv_obj_set_align(ui_SN2PNL1BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL1BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN2PNL1BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_SN2PNL1BTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL1BTN1LAB1 = lv_label_create(ui_SN2PNL1BTN1);
    lv_obj_set_width(ui_SN2PNL1BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL1BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN2PNL1BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL1BTN1LAB1, "下一步");
    lv_obj_set_style_text_color(ui_SN2PNL1BTN1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL1BTN1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL1BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL1BTN2 = lv_btn_create(ui_SN2PNL1);
    lv_obj_set_width(ui_SN2PNL1BTN2, 114);
    lv_obj_set_height(ui_SN2PNL1BTN2, 53);
    lv_obj_set_x(ui_SN2PNL1BTN2, -149);
    lv_obj_set_y(ui_SN2PNL1BTN2, 245);
    lv_obj_set_align(ui_SN2PNL1BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL1BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN2PNL1BTN2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN2PNL1BTN2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN2PNL1BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2PNL1BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN2PNL1BTN2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN2PNL1BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL1BTN2IM1 = lv_img_create(ui_SN2PNL1BTN2);
    lv_img_set_src(ui_SN2PNL1BTN2IM1, &ui_img_1506316136);
    lv_obj_set_width(ui_SN2PNL1BTN2IM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL1BTN2IM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL1BTN2IM1, -38);
    lv_obj_set_y(ui_SN2PNL1BTN2IM1, 4);
    lv_obj_set_align(ui_SN2PNL1BTN2IM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL1BTN2IM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_SN2PNL1BTN2IM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_SN2PNL1BTN2LAB1 = lv_label_create(ui_SN2PNL1BTN2);
    lv_obj_set_width(ui_SN2PNL1BTN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL1BTN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL1BTN2LAB1, 14);
    lv_obj_set_y(ui_SN2PNL1BTN2LAB1, 7);
    lv_obj_set_align(ui_SN2PNL1BTN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL1BTN2LAB1, "設置");
    lv_obj_set_style_text_font(ui_SN2PNL1BTN2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_SN2PNL2, 480);
    lv_obj_set_height(ui_SN2PNL2, 800);
    lv_obj_set_align(ui_SN2PNL2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL2, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN2PNL2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_SN2PNL2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN2PNL2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2PNL2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL3 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_SN2PNL3, 410);
    lv_obj_set_height(ui_SN2PNL3, 225);
    lv_obj_set_x(ui_SN2PNL3, 5);
    lv_obj_set_y(ui_SN2PNL3, -10);
    lv_obj_set_align(ui_SN2PNL3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL3, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_SN2PNL3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_SN2PNL3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN2PNL3, lv_color_hex(0xF00000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN2PNL3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN2PNL3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL3LAB1 = lv_label_create(ui_SN2PNL3);
    lv_obj_set_width(ui_SN2PNL3LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL3LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL3LAB1, 0);
    lv_obj_set_y(ui_SN2PNL3LAB1, -55);
    lv_obj_set_align(ui_SN2PNL3LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL3LAB1, "請輸入客戶資料");
    lv_obj_set_style_text_color(ui_SN2PNL3LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL3LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL3LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL3LAB2 = lv_label_create(ui_SN2PNL3);
    lv_obj_set_width(ui_SN2PNL3LAB2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL3LAB2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL3LAB2, 0);
    lv_obj_set_y(ui_SN2PNL3LAB2, -15);
    lv_obj_set_align(ui_SN2PNL3LAB2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL3LAB2, "客戶資料不可留空");
    lv_obj_set_style_text_color(ui_SN2PNL3LAB2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL3LAB2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL3LAB2, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL3BTN1 = lv_btn_create(ui_SN2PNL3);
    lv_obj_set_width(ui_SN2PNL3BTN1, 70);
    lv_obj_set_height(ui_SN2PNL3BTN1, 30);
    lv_obj_set_x(ui_SN2PNL3BTN1, 0);
    lv_obj_set_y(ui_SN2PNL3BTN1, 50);
    lv_obj_set_align(ui_SN2PNL3BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL3BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN2PNL3BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN2PNL3BTN1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN2PNL3BTN1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2PNL3BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SN2PNL3BTN1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SN2PNL3BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL3BTN1LAB1 = lv_label_create(ui_SN2PNL3BTN1);
    lv_obj_set_width(ui_SN2PNL3BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL3BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN2PNL3BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL3BTN1LAB1, "確認");
    lv_obj_set_style_text_color(ui_SN2PNL3BTN1LAB1, lv_color_hex(0xF00000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL3BTN1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL3BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL4 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_SN2PNL4, 486);
    lv_obj_set_height(ui_SN2PNL4, 806);
    lv_obj_set_align(ui_SN2PNL4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL4, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_SN2PNL4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_SN2PNL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN2PNL4, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2PNL4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL4PNL1 = lv_obj_create(ui_SN2PNL4);
    lv_obj_set_width(ui_SN2PNL4PNL1, 420);
    lv_obj_set_height(ui_SN2PNL4PNL1, 260);
    lv_obj_set_x(ui_SN2PNL4PNL1, 0);
    lv_obj_set_y(ui_SN2PNL4PNL1, -30);
    lv_obj_set_align(ui_SN2PNL4PNL1, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_SN2PNL4PNL1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_SN2PNL4PNL1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_SN2PNL4PNL1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2PNL4PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SN2PNL4PNL1, lv_color_hex(0x06FC41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SN2PNL4PNL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SN2PNL4PNL1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL4PNL1BTN1 = lv_btn_create(ui_SN2PNL4PNL1);
    lv_obj_set_width(ui_SN2PNL4PNL1BTN1, 120);
    lv_obj_set_height(ui_SN2PNL4PNL1BTN1, 70);
    lv_obj_set_x(ui_SN2PNL4PNL1BTN1, -85);
    lv_obj_set_y(ui_SN2PNL4PNL1BTN1, 60);
    lv_obj_set_align(ui_SN2PNL4PNL1BTN1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL4PNL1BTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN2PNL4PNL1BTN1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN2PNL4PNL1BTN1, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN2PNL4PNL1BTN1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2PNL4PNL1BTN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL4PNL1BTN1LAB1 = lv_label_create(ui_SN2PNL4PNL1BTN1);
    lv_obj_set_width(ui_SN2PNL4PNL1BTN1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL4PNL1BTN1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN2PNL4PNL1BTN1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL4PNL1BTN1LAB1, "確認");
    lv_obj_set_style_text_font(ui_SN2PNL4PNL1BTN1LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL4PNL1BTN2 = lv_btn_create(ui_SN2PNL4PNL1);
    lv_obj_set_width(ui_SN2PNL4PNL1BTN2, 120);
    lv_obj_set_height(ui_SN2PNL4PNL1BTN2, 70);
    lv_obj_set_x(ui_SN2PNL4PNL1BTN2, 85);
    lv_obj_set_y(ui_SN2PNL4PNL1BTN2, 60);
    lv_obj_set_align(ui_SN2PNL4PNL1BTN2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2PNL4PNL1BTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_SN2PNL4PNL1BTN2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_SN2PNL4PNL1BTN2, 13, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SN2PNL4PNL1BTN2, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2PNL4PNL1BTN2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL4PNL1BTN2LAB1 = lv_label_create(ui_SN2PNL4PNL1BTN2);
    lv_obj_set_width(ui_SN2PNL4PNL1BTN2LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL4PNL1BTN2LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_SN2PNL4PNL1BTN2LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL4PNL1BTN2LAB1, "取消");
    lv_obj_set_style_text_font(ui_SN2PNL4PNL1BTN2LAB1, &ui_font_HEI32x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2PNL4PNL1LAB1 = lv_label_create(ui_SN2PNL4PNL1);
    lv_obj_set_width(ui_SN2PNL4PNL1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2PNL4PNL1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2PNL4PNL1LAB1, 0);
    lv_obj_set_y(ui_SN2PNL4PNL1LAB1, -50);
    lv_obj_set_align(ui_SN2PNL4PNL1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2PNL4PNL1LAB1, "是否確認關機");
    lv_obj_set_style_text_color(ui_SN2PNL4PNL1LAB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2PNL4PNL1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2PNL4PNL1LAB1, &ui_font_HEI50x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SN2KB1 = lv_keyboard_create(ui_Screen2);
    lv_keyboard_set_mode(ui_SN2KB1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_SN2KB1, 475);
    lv_obj_set_height(ui_SN2KB1, 308);
    lv_obj_set_x(ui_SN2KB1, 0);
    lv_obj_set_y(ui_SN2KB1, 245);
    lv_obj_set_align(ui_SN2KB1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2KB1, LV_OBJ_FLAG_HIDDEN); /// Flags
    // lv_obj_set_style_bg_color(ui_SN2KB1, lv_color_hex(0xC7C8CA), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_SN2KB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SN2KB1, lv_color_hex(0x002855), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SN2KB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_SN2KB1, &lv_font_montserrat_32, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_SN2ARC1 = lv_arc_create(ui_Screen2);
    lv_obj_set_width(ui_SN2ARC1, 93);
    lv_obj_set_height(ui_SN2ARC1, 118);
    lv_obj_set_x(ui_SN2ARC1, 179);
    lv_obj_set_y(ui_SN2ARC1, -93);
    lv_obj_set_align(ui_SN2ARC1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SN2ARC1, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_arc_set_value(ui_SN2ARC1, 100);

    ui_SN2ARC1LAB1 = lv_label_create(ui_SN2ARC1);
    lv_obj_set_width(ui_SN2ARC1LAB1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SN2ARC1LAB1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SN2ARC1LAB1, -1);
    lv_obj_set_y(ui_SN2ARC1LAB1, 38);
    lv_obj_set_align(ui_SN2ARC1LAB1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SN2ARC1LAB1, "電量測試");
    lv_obj_set_style_text_color(ui_SN2ARC1LAB1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SN2ARC1LAB1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SN2ARC1LAB1, &ui_font_HEI22x4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SN2LAB1, ui_event_SN2LAB1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN2PNL1TXT1, ui_event_SN2PNL1TXT1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN2PNL1TXT2, ui_event_SN2PNL1TXT2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN2PNL1BTN1, ui_event_SN2PNL1BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN2PNL1BTN2, ui_event_SN2PNL1BTN2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN2PNL1, ui_event_SN2PNL1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN2PNL3BTN1, ui_event_SN2PNL3BTN1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN2KB1, ui_event_SN2KB1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN2ARC1, ui_event_SN2ARC1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_SN2PNL4PNL1BTN1, ui_event_Shutdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SN2PNL4PNL1BTN2, ui_event_Cancel, LV_EVENT_ALL, NULL);
}
